### ISSUE TITLE
Suggestion: Bonus modifiers + possible armor types

### ISSUE THREAD

**Issue by Soldra** [TheIllusiveC4/ConstructsArmory#10]
As it stands, one of the small improvements possible for this mod is making creative modifiers usable on armor to allow more op equipment.

Another useful thing (for later, just work on it at your own pace) would be different armor types, so here are some suggestions:

Heavy armor, needing more materials, slowing you down but having higher defensive values and potentially more traits

Boost armor which increases your movement speed and/or jump height, but is not as protective

Sealed armor which grants poison, wither and drowning resistance, but is rather weak.

Also, please make the armor nether star compatible, because losing it due to minizombies is annoying.

**Comment by TheIllusiveC4** [comment]
1) Do you mean creative modifiers like the one for tools in Tinkers' Construct? Or are you talking about something else?

2) I've had to think really hard about this when I was first formulating the design of this mod. The problem with different armor types is that armor isn't as abstract as tools are. There are numerous possible functions for tools, but armor all comes down to protecting the wearer from damage and there are only so many ways to accomplish this. Many of the ways that armor could be differentiated can simply be another modifier or through traits.
That being said, I'm not crossing out the possibility. If I ever figure out a way to introduce an armor set that is different enough to justify its existence, I'll gladly implement it. I have a few ideas that I'm toying with, but this is something I'll have to work on later after the foundations are a little more solid.

3) The Nether Star modifier will definitely be in the next update.

**Comment by ElvenChaos** [comment]
1. I think having the creative modifiers from TCon function on CA armor is the intention, and is a viable inclusion.

2. I think traits and modifiers take this space up fairly well. The real-life trade-off with different real armors is a balance of "how well does it protect me" and "how much does it get in my way." While armors in minecraft do not tend to have a "this is super-protective, but it is going to weigh you down or slow down your action speed," having a material that is low protection with a speed bonus covers this suggestion.
Though, if you want different armors, you could implement different _aesthetic_ armors, which would be nice as a future feature after the mod is out of alpha. This would just be different meshes/sprites with different material-layers, not functionally different in any way to the vanilla-looking armor. Shogun armor similar to Thaumcraft, anyone?
