### ISSUE TITLE
Aquaspeed decreases swim speed in flowing water.

### ISSUE THREAD

**Issue by LtCassiopeia** [TheIllusiveC4/ConstructsArmory#101]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.0.2
* Tinkers' Construct: 2.10.1.87
* Mantle: 1.3.2.24
* Forge: 14.23.4.2738

#### Observed Behavior:
Decreased swim speed in flowing water while wearing Prismarine armor. (each piece of armor appears to decrease speed by additional 30%) 

#### Expected Behavior:
Increased or unchanged swim speed in flowing water while wearing Prismarine armor.

#### Steps to Reproduce:
1. Craft and equip armor with the Aquaspeed trait.
2. Place or find water flowing in column at least 3 blocks high. (only one block need be flowing water)
3. Attempt swimming upward using spacebar.

**Comment by TheIllusiveC4** [comment]
The behavior of the swim speed modifications will be changed in the next update, and a consequence of this is that it will operate correctly in flowing water.

**Comment by TheIllusiveC4** [comment]
Fixed in 0b76bcb6a8e15a96bd7531189e2fa39e15d6c78a
