### ISSUE TITLE
Invigorating not persisting between Log out and Log in. 

### ISSUE THREAD

**Issue by Gunner76th** [TheIllusiveC4/ConstructsArmory#103]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.0.1.2
* Tinkers' Construct: 1.12.2-2.10.1.87
* Mantle: 1.12-1.3.2.24
* Forge: 1.12.2-14.23.4.2738

#### Observed Behavior:
When wearing armor (full set) with the Invigorating enhancement Hearts will be at +8 yellow hearts while logged in. However if you log out, then later on log back in, all yellow hearts are gone causing you to consume hunger to replenish the missing 8 hearts. 
#### Expected Behavior:
While wearing armor (full set) with the Invigorating enhancement Hearts will be at +8 yellow hearts. Upon logging out and subsequently logging back in all hearts should remain since no damage was taken and armor was not removed to cause loss of hearts. 
#### Steps to Reproduce:
1. Construct a full set of armor that has the Invigorating enhancement on it (My armor in question receives it from Knightslime Armor Plates). 
2. Wait until hearts are full (10 red + 8 yellow) 
3. Log out and log back in and observe that hearts are back down to 10 red hearts only. Since the Invigorating is not a potion effect, and is instead more similar to the older TCon Heart Canisters the added hearts should be permanent in so long as the armor is being worn, in the same way that the heart canisters were applied. 

The problem this issue creates is when you have both Tasty and Invigorating both on the armor. Upon login your armor instantly starts taking durability loss as you start consuming your armor due to the armor bonus of Invigorating consuming hunger to bring your hearts back up to +8 yellow hearts. If the Invigorating enhancement was applied similar to the heart canisters from TCon, the +8 yellow hearts would persist between log outs/ins and thus no loss of hearts would be incurred. This can also present a problem should the player lose a connection in an area of danger (multiple enemies or engaging a boss) where the extra hearts might have provided sufficient health to survive attacks, however with the loss of said hearts on login, the player could now be victim to death as a result. 
...

**Comment by TheIllusiveC4** [comment]
This is due to the fact that, on being loaded back into a world, entities have their health values set before their health maximums are fully initialized. I'll have to think about the best way to work around this.
