### ISSUE TITLE
Missing File Errors on Startup

### ISSUE THREAD

**Issue by Eogen** [TheIllusiveC4/ConstructsArmory#108]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.0.1.2.jar
* Tinkers' Construct: TConstruct-1.12.2-2.10.1.87.jar
* Mantle: Mantle-1.12-1.3.2.24.jar
* Forge: forge-1.12.2-14.23.4.2705-universal.jar
* Minecraft: minecraft_server.1.12.2.jar

#### Observed Behavior:

Errors in startup log.  I know this is not the recently released version, but I did not see anything in the changelog, and had issues trying to go to the newer than release version of Forge.

Error Repeats for:
* conarm:models/item/modifiers/malachite_armor.json
* conarm:models/item/modifiers/tanzanite_armor.json
* conarm:models/item/modifiers/runemana_armor.json
* conarm:models/item/modifiers/topaz_armor.json
* conarm:models/item/modifiers/dragonstone_armor.json
* conarm:models/item/modifiers/ruby_armor.json
* conarm:models/item/modifiers/sapphire_armor.json
* conarm:models/item/modifiers/amber_armor.json
* conarm:models/item/modifiers/amethyst_armor.json
* conarm:models/item/modifiers/peridot_armor.json

> [main/ERROR]` [tconstruct-modifier]: Cannot load modifier-model conarm:models/item/modifiers/amethyst_armor
> java.io.FileNotFoundException: conarm:models/item/modifiers/amethyst_armor.json
> 	at net.minecraft.client.resources.FallbackResourceManager.getResource(FallbackResourceManager.java:69) ~[cei.class:?]
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
> 	at slimeknights.tconstruct.library.client.model.ModelHelper.getReaderForResource(ModelHelper.java:79) ~[ModelHelper.class:?]
> 	at slimeknights.tconstruct.library.client.model.ModelHelper.getReaderForResource(ModelHelper.java:74) ~[ModelHelper.class:?]
> 	at slimeknights.tconstruct.library.client.model.ModelHelper.loadTexturesFromJson(ModelHelper.java:84) ~[ModelHelper.class:?]
> 	at slimeknights.tconstruct.library.client.model.ModifierModelLoader.loadFilesIntoCache(ModifierModelLoader.java:150) [ModifierModelLoader.class:?]
> 	at slimeknights.tconstruct.library.client.model.ModifierModelLoader.loadModel(ModifierModelLoader.java:78) [ModifierModelLoader.class:?]
> 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) [ModelLoaderRegistry.class:?]
> 	at c4.conarm.client.utils.ArmorModelLoader.loadModel(ArmorModelLoader.java:150) [ArmorModelLoader.class:?]
> 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) [ModelLoaderRegistry.class:?]
> 	at net.minecraftforge.client.model.ModelLoader.loadItemModels(ModelLoader.java:304) [ModelLoader.class:?]
> 	at net.minecraft.client.renderer.block.model.ModelBakery.loadVariantItemModels(ModelBakery.java:175) [cgb.class:?]
> 	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:153) [ModelLoader.class:?]
> 	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [cgc.class:?]
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [cev.class:?]
> 	at net.minecraft.client.Minecraft.init(Minecraft.java:512) [bib.class:?]
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:3926) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by TheIllusiveC4** [comment]
Strictly speaking, this is not a Construct's Armory issue since the base mod does not add these modifiers and anything I do on my end would not directly address the issue. 

This is either an oversight from the third-party or an oversight in my API design, but it's hard to tell with just the information presented. 

Contact the developer of the add-on that adds these modifiers and they would be able to shed more light on this issue, which then may or may not lead back to me.
