### ISSUE TITLE
Add "Broken" rendering to armor

### ISSUE THREAD

**Issue by Gunner76th** [TheIllusiveC4/ConstructsArmory#109]
At present, if your armor breaks there is no graphical representation of this unless you hover over your armor and hold down Shift. I am suggesting that the armor item's render mechanic be similar to that of Tinkers Construct tools and weapons in that when the item is broken its graphical rendering makes it appear as such. 

I was just about to file a bug report for my helmet no longer working thinking there was a bug with the code that was causing it to  stop rendering entirely, as well as no longer provide its abilities (Amphibious and Night Vision). It wasn't until I went to see what materials I had used to make it so that I could make an entirely new one, that I saw instead of a number for Durability it simply said BROKEN. Providing a clear rendering to indicate a broken piece of armor instead of making it stop rendering entirely would be both more in line with Tinkers Construct (which Constructs Armory is based on) and provide the players with a better indication as to why their armor has stopped working. 

![image](https://user-images.githubusercontent.com/5566872/44996186-780d3a00-af74-11e8-80a8-be819f93da44.png)

**Comment by TheIllusiveC4** [comment]
Yeah, this has been something I've been meaning to add.

**Comment by ahmetsalihkaya** [comment]
Textures are little broken :/ 
![2018-09-16_13 21 14](https://user-images.githubusercontent.com/43313563/45595399-a991f680-b9b3-11e8-9b23-8d827d0eb9d5.png)
![2018-09-16_13 21 10](https://user-images.githubusercontent.com/43313563/45595401-adbe1400-b9b3-11e8-9176-df341c40a0d0.png)

**Comment by TheIllusiveC4** [comment]
@NeonGraphicsTR 
Please report your issue in a separate thread, as your issue has nothing to do with this suggestion.
