### ISSUE TITLE
Crash Compatibility with EnderIO 1.12

### ISSUE THREAD

**Issue by ivardensphere** [TheIllusiveC4/ConstructsArmory#11]
Forge version: 14.23.2.2623
Minecraft Version: 1.12.2
Conarm Version: conarm-1.12.2-0.0.6-a.jar

Client crashes on load with the newest build of enderIO. 

I believe it is a similiar issue to https://github.com/TheIllusiveC4/ConstructsArmory/issues/1 on with the newest enderIO adding a trait "Enderport" to tinker's construct (see https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-integration-tic/src/main/java/crazypants/enderio/integration/tic/traits/TraitTeleport.java for reference).

crashlog:
https://pastebin.com/20eQXb73

Let me know if you need more info.

**Comment by TheIllusiveC4** [comment]
Yep, your conjecture is correct. And here I thought I was being clever with the name "Enderport".
This is an easy fix, I just have to change the name. This does mean that everyone with Enderport armor will have to remake it once that happens. Maybe I should consider just appending "_armor" to all my trait identifiers to avoid most of these issues.

**Comment by TheIllusiveC4** [comment]
Fixed in 660fe07d8bf607abf28521809f0387b7c83ccdcd
Most armor will need to be remade, but this should also avoid any of these issues in the future
