### ISSUE TITLE
[Suggestion] Crafttweaker method to change traits

### ISSUE THREAD

**Issue by Mike-U5** [TheIllusiveC4/ConstructsArmory#110]
Is it feasible to add a crafttweaker method to change traits? Or will this cause technical difficulties.
Something like

\<conarm:wood\>.removeTraits();                _//Removes all traits._
\<conarm:wood\>.addTrait("ecological");     _//Adds a trait._
\<conarm:wood\>.addCoreTrait("chucker");  _//Adds a trait to Core part only._

**Comment by TheIllusiveC4** [comment]
Unfortunately, Tinkers' does not allow this kind of editing of traits so it's out of my hands.
