### ISSUE TITLE
Amphibious breath indicator

### ISSUE THREAD

**Issue by Haaxor1689** [TheIllusiveC4/ConstructsArmory#116]
Hi there,
it would be nice to be able to see how much air is stored with the Amphibious enchantment on. Maybe when you Shift + hover over the item under the armor piece stats.

**Comment by TheIllusiveC4** [comment]
Alright sure, I can do that.

**Comment by TheIllusiveC4** [comment]
This won't be included in the exact manner you requested, but the amount of stored air will show as extra information in the armor stats when you place the armor in the Armor Station/Forge. This is in line with how the Mending Moss modifier displays the stored XP information.

**Comment by Haaxor1689** [comment]
Thanks for the quick response and delivery :). And yeah including it in the Armor Forge extended info makes more sense to keep it consistent.
