### ISSUE TITLE
Just an little suggestion

### ISSUE THREAD

**Issue by Legegends** [TheIllusiveC4/ConstructsArmory#117]
The way that the parasitic modifier work is realy annoying like it takes your HP even when  it lost one in durability taking your hp when and reparing less (<--- this can be realy annoying when you have all the 4 pieces with the modifier)
           The way it takes your hp it looks like you take damage from something, and that can be realy annoying when you're in your base, like you take damage it aways look like you took it from a mob or got hit by an arrow (realy annoying gotta say, it can make you paranoic too kek) 

Some ideas to change that:
1. When crouthing after a few seconds the armor will start taking your Hp and repairing iteself.

2. Only takes HP when it needs like if it lost 5 in durability it will take the hp not if less.

3. Changing the way it shows you that it took your life to reapir itself, showing a whiter effect in the heart can be realy cool and not by shaking the screen like it does rn.

**Comment by TheIllusiveC4** [comment]
The Parasitic modifier was already changed in version 1.0.2 to not steal health. Instead, it adds exhaustion when it heals itself.
