### ISSUE TITLE
Traits bug ?

### ISSUE THREAD

**Issue by dewobedil** [TheIllusiveC4/ConstructsArmory#118]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.1.1
* Tinkers' Construct: TConstruct-1.12.2-2.10.1.87
* Mantle: Mantle-1.12-1.3.2.24
* Forge: 14.23.4.2760

#### Observed Behavior:
Video for explain more https://youtu.be/x5IfkvzI38g
#### Expected Behavior:
Knightslime is too OP is this bug ?
#### Steps to Reproduce:
1. Using only chestplate and legging
2.
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).
none

**Comment by TheIllusiveC4** [comment]
Definitely a bug. I'll get to work on a fix for that.
