### ISSUE TITLE
Suggestion Embossment Config

### ISSUE THREAD

**Issue by RoyalReject** [TheIllusiveC4/ConstructsArmory#122]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: Any
* Tinkers' Construct: Any
* Mantle: Any
* Forge: Any

#### Observed Behavior:
I think it would be nice to have a config value of how many embossments to allow such that if players wanted they could get a lot more of the adhancments onto armor.
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
The embossments are meant to mimic the embossment of Tinkers' tools, which do not have this config option as far as I recall. So I will not be adding this option either. In addition, if you're looking to add more modifiers onto armor, that functionality is largely fulfilled by the [Tinkers' Tool Leveling](https://minecraft.curseforge.com/projects/tinkers-tool-leveling) mod.

**Comment by RoyalReject** [comment]
I dont think you understood what i was trying to say. I want to be able to emboss on a tool more than once, some tools only have certain attributes on there parts which are not accessible through modifiers

**Comment by TheIllusiveC4** [comment]
If you want to emboss on a _tool_ more than once, you should be asking the Tinkers' developers as I only handle the armor.
