### ISSUE TITLE
Suggestion: non-entity Armor stand due to vanilla being an entity

### ISSUE THREAD

**Issue by Thunder-Nova** [TheIllusiveC4/ConstructsArmory#124]
It is not a side mod need suggestion, but I will use another mod as exemple. Bibliocraft's armor stand. If you know the vanilla armor stand it is an entity, meaning that it has a risk of despawning, or be deleted by server side clear entities.

#### This suggestion does not require other mods, and you can add your own twist to it. Since you focus purely in armor, tinker, and vanilla.
Such as instead of an armor stand looking thing, it can be more dummy (uses leather and haybales) or/and statue like (uses stone). 

If you do add arms, for the statue model, I suggest 3 poses: arms down, T-Pose or/and Zombie pose. I remember the statue mod I used to love in 1.3.2. But I will suggest to keep it simple, so it is easier to fix.

No arms: same as vanilla recipe but instead of sticks, can be stone
T-Pose: same as above but slabs on both sides on the top.
Zombie: Same as T-Pose but slabs in the middle instead of top.
Arms down: No arms recipe but the bottom sides slabs are stone (makes sence slab+slab=full block.)

If you do make a dummy one, I would love it that it show damage values if hit by a weapon, and if armor is equiped it can actually show the change in damage value. But I won't suggest to make it. But it does make it interesting that we can test both armor and weapons effectiveness.

The idea is simply to have a display of how good the armor looks with the risk of losing it. In the case of TiCon the item rack does the job, since most tools are flat, yet the armor is 3D and nice to look at.

**Comment by TheIllusiveC4** [comment]
While this is an interesting idea, this is something I'd rather have as a separate mod instead of adding it to Construct's Armory.

**Comment by Thunder-Nova** [comment]
Understandable
