### ISSUE TITLE
BUG: Constructs Armory Disables TCon Modifier

### ISSUE THREAD

**Issue by Boolyman** [TheIllusiveC4/ConstructsArmory#13]
Hey bud, did some troubleshooting today to find out why the Beheading weapon modifier (Obsidian + Ender Pearl) was not working in Tinkers Construct anymore.  It is supposed to add 10% beheading per level.  But when the obsidian and ender pearl are placed in the tool forge with a weapon, an error message comes up in the GUI.  

Turns out whenever Constructs Armory is installed, that Tinker's weapon modifier refuses to work.  Could it have something to do you using Obsidian for a modifier in your addon mod?

**Comment by TheIllusiveC4** [comment]
> Could it have something to do you using Obsidian for a modifier in your addon mod?

Yeah, going by some previous issues, this seems to be the case. As far as I can tell, TCon doesn't like items being associated with more than one modifier. I thought that this only applied when the recipe matched exactly, but it looks like that's not the case and anything associated with two different modifers will bug out. Perhaps this is why TCon made the Reinforced Plate a unique item crafted with Obsidian to work around this limitation? Anyways, I'll try and work on a workaround.

**Comment by TheIllusiveC4** [comment]
A note about the latest commit that closed this issue: Since I know you were interested in the ability to rebalance the modifiers, the shift to using crafted items instead of raw materials for the armor modifiers allows you to use CraftTweaker to modify those recipes to suit your needs.
