### ISSUE TITLE
Constructs Armory ContentTweaker does not register non-custom traits.

### ISSUE THREAD

**Issue by duhadventure** [TheIllusiveC4/ConstructsArmory#132]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.0.1
* Tinkers' Construct: 2.10.1.87
* Mantle:  1.3.2.24
* Forge: 2768
* ContentTweaker: 4.8.0

#### Observed Behavior:
When trying to add traits that already exist ingame it will say it cannot identify them.

#### Expected Behavior:
Trait would be added to material for armor. 

#### Steps to Reproduce:
1. Create a contenttweaker script ([using a modified version of Dragnier's](https://pastebin.com/Z7D1YeRj))
2. Attempt to substitute the mana modifier with any other tinkers modifier, like duritos or duritos_ranch_armor
3. Neither will work, even if you use try to take out the _armor and leave it as duritos_ranch or just duritos, it will tell you this if you use duritos_ranch_armor (and I used contenttweaker and tinkers extras to make sure these were the modifier IDs:
`[13:35:09] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ERROR: Cannot identify trait <conarmtrait:duritos_ranch_armor_armor>
[13:35:09] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ERROR: [contenttweaker]: Error executing {[0:contenttweaker]: Materials.zs}: null`
...

Crash Log: Forced Crash https://pastebin.com/5eMx0npJ

**Comment by TheIllusiveC4** [comment]
Did you try using strings instead of brackets? For instance, instead of `<conarmtrait:duritos_ranch>`, just put `duritos_ranch`.

**Comment by duhadventure** [comment]
No that didnt work either
Used duritos_ranch and conarmtrait:duritos_ranch_armor and conarmtrait:duritos_ranch
![image](https://user-images.githubusercontent.com/8278338/47971134-02951700-e054-11e8-84d1-630bf17d54db.png)

**Comment by TheIllusiveC4** [comment]
Just to be sure, did you put something like:
`rcMat.addMaterialTrait("duritos_ranch", "core");`
The quotes is important, I failed to mention that in my previous comment.

**Comment by duhadventure** [comment]
Yea that didnt work either
![image](https://user-images.githubusercontent.com/8278338/48018186-cf0ac900-e0f5-11e8-8f86-dfca815e4d1a.png)

**Comment by TheIllusiveC4** [comment]
Sorry, just one more thing, can you try: `rcMat.addMaterialTrait("duritos_ranch_armor", "core");`
If that doesn't work, then I'll have to be do some testing.

**Comment by duhadventure** [comment]
> Sorry, just one more thing, can you try: `rcMat.addMaterialTrait("duritos_ranch_armor", "core");`
> If that doesn't work, then I'll have to be do some testing.

That one seems to have worked. Also, do they modifiers have to bee specifically for armor or can it use the tool modifiers as armor modifiers. (Like the mana modifier)

**Comment by TheIllusiveC4** [comment]
I think you can use tool traits as well but I'm not 100% sure.
