### ISSUE TITLE
 More armor types (yea I read your answer, just something that is nagging me)

### ISSUE THREAD

**Issue by Thunder-Nova** [TheIllusiveC4/ConstructsArmory#134]
#### I did read this, so don't worry.
```
Q. Are you going to have different armor types?

A. No. Armor isn't quite as abstract as tools are, and any way that I can think of to differentiate armor is already handled by the traits/modifiers system. There is room however for add-ons to possibly implement cosmetic alternatives.
```

Armor might not be as abstract as tools, but I felt 2 armor type set that been bothering me.

I will consider the armor set you have currently as Heavy Armor set for this purposes.

Heavy armor can stack up on both modifiers and accessories, good defense.

Light armor has less defense, and can't use protection modifiers. If this was added heavy armor should get a small speed penalty, due to being... heavy. Light armor gains a bigger bonus in speed upgrades.

Robes, this set like the light armor has less defense, and can't use defense upgrades. They can't use metals as parts instead of their cores. But when upgraded, they will still look the same. Accessories won't show up on the surface. Dyed leather has 4 effects seperated between their colors.
 - Blue, Cyan, Light blue, black: (Ninja) Player gains full invisibly when not moving for 3 seconds at night.
 - Red, Orange, Yellow, Pink, Purple, Magenta: (Hellbent) Player gains fire resistance in the nether.
 - Green, Lime, brown: (Forest Dweller) Passive mobs will follow.
 - White, light gray, gray: (Writable) pretty much self explanatory

This is mainly in contrast to where we've been with the suggestions and one of the issues you had with dyes. So the robes, was mainly put for: "heck, it's a hidden type armor, so basically it's based on the cover part, not the core and accessories as cosmetic."

I won't push this, so feel free to close this.

**Comment by TheIllusiveC4** [comment]
Don't worry, I'm open to discussing anything in the FAQ, as long as the suggestion itself goes deeper than the question in the FAQ itself.

The problem I have with the Heavy/Light armor distinction is that people always suggest the same thing, which is that Heavy armor imposes a speed penalty and Light armor doesn't or even gives a small speed boost. I personally feel that speed penalties on worn armor in a game like Minecraft is an incredibly unfun feeling and just motivates players to wear other armor, regardless of protection capabilities.

The suggestion about Robes and dyeing is interesting, but ultimately I feel like it moves too far away from both Tinkers and ConArm and would be more at home in its own separate ecosystem.

**Comment by Thunder-Nova** [comment]
@TheIllusiveC4
Yea, I do agree. 100%

I did think that with the encouragement of speed boost modifier on heavy armor. But like any tool and armor there should be a positive with a negative on equal terms. Exemple: Cleaver High damage output and beheading, yet has a slow attack. Rapier fast and piercing, but attack boosting modifier gets seriously reduced.

My main point was mainly reflecting on the 3 main swords of tinker by nostalgia stand point. Rapier, longsword, and broadsword. In reflect: Robe, light, heavy.

About the robe yea, I felt a bit apart from Tinker, but still within which I will explain. I forgot to mention it should be an armor immune to armor piercing if full set. Weak defense, but great in pvp saves. (I for one uses rapier a lot in public servers, due to it's ability and speed, would love to see a counter.)

Seen a lot of actual sword fights (even though it is seems an act, the people do it for research) and leather robes and capes tends to makes things very hard against rapier users due to blocking the jointed areas where most armors are weak at yet the robes and capes are used to manipulate the trajectories of piercing strikes due to how loose they are.

So I figured talking about it as a tinker weapon counter fits well in this mod that has tinker armor. If you get where I am going.

**Comment by TheIllusiveC4** [comment]
I do agree that having both positive and negative traits across different types of items is ideal. I just don't think that movement speed is necessarily the best one to utilize for armor, for the reasons mentioned above. Ideally, I would like to have different types of armor sets to match the variety that Tinkers does, but I haven't figured out a good way to do it.

Armors immune to armor piercing isn't really a good idea in practice since they would also protect from things they probably shouldn't, like void damage, due to the very simple Minecraft damage system.

**Comment by Thunder-Nova** [comment]
Yea, speed is an issues. Though can make heavy armor without the speed penalty, but it gets a bigger penalty in speed modifiers. Such as rapiers and damage modifiers.

I pretty much guess rapier does void damage for armor piercing. I wonder if it is possible to make void defense instead of immunity. Since the rapier's damage does reflect itself, such as 10 void damage still gives 10 void damage. So how about the robe armor reflects it's defense also in void ex: 10 defence = 10 normal defense + 10 void defense. This is especially good against rapiers being double defended, but not other weapons. People still gets hurt when hit by impacts.

I am curious, if you can make a void defense (not immunity), and jump in the void to see it's effect. I know the Chaos Dragon from Draconic Evolution does void damage and can pretty much one shot anyone not wearing the draconic armors. Not saying implimenting the mod into yours, but use it to test out. If player can still die in the void at least and still defend against rapiers, I will definitely think of it of a success. And perhaps you can use it as modifiers or a new armor set. Up to you.

**Comment by TheIllusiveC4** [comment]
Hm, you do bring up a fair point about the change in modifier increments based on equipment type. I'll have to look into it a little bit more to test its viability.

It's not quite that rapier does void damage. Minecraft's damage system has a certain tag, 'Unblockable', that governs whether or not armor should affect that particular damage type. Rapiers and void damage utilize this tag, but they are still different damage types. The issue I brought up before is that in order to defend against rapiers, I have to essentially defend against any damage type that tags itself as 'Unblockable', which can have some undesired side effects. There's the possibility that I could check for the rapier item itself on the attacker, but this is a bit hacky and in the end I think it's too close to starting an arms race between armor penetration and armor defense.

**Comment by Thunder-Nova** [comment]
Thanks

Yea... I do recall seeing in an nbt editor long time ago about unblockable since you brought it up. Barely touched the editor instead for removing items that crashed players in servers.

I am stumped, but I am hopeful in this one. Unblockable by itself might be a problem, but it might be possible to add a form of conditional defense. Such as "if", "else", "add", and so on... But that is just based on my experience on Excel. Idk of how most mod editing works. I want to avoid any OP overall system, but a counter to an existing OP. And the rapier itself is OP in PvP. The only armors I was able to counter against rapiers was infinity armor, and armors with shields such as draconic armor. I am guessing they are immune to unblockables and they are OP. So I do agree there should be something other then immunity. Do think it's something to experiment on. And as a seperate mod, before balancing and make it into this mod.

**Comment by kierajreed** [comment]
The problem is always going to be "should the unblockable attack penetrate impenetrable armor, or not?". So just don't create things that try to be all-powerful. The best balance is rock-paper-scissors.

**Comment by Thunder-Nova** [comment]
That is pretty much the idea of the multi types of armor
