### ISSUE TITLE
Compatibility issue with Thermal Expansion´ augment: flux reconstruction

### ISSUE THREAD

**Issue by Eldhelion** [TheIllusiveC4/ConstructsArmory#135]
I´m playing on FTB direwold20 2.3.0 for minecraft 1.12.
Thermal Expansion add a dozen machines, that may receive a specialization on a task, one of wich is the "energetic infuser" that with the " flux reconstruction" specialization, consume energy and liquid xp to repair durability

#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.0.1
* Tinkers' Construct: 1.12.2-2.10.1.87
* Mantle: 1.3.2.24
* Forge: 14.23.4.2760

#### Observed Behavior:
Repairing a broken item, result in a item with full durability, but with the "broken" flag in its NBT, in other words, for all purposes, the itens still out of operation, no modifier are aplied to the player.

As thermal have no way of knowing the custom nbt of this mod, I tried te normal repair at the "Armor station".
when putting the item, and its repair material, a result appear on the output, bug getting the item does not consume the repair material, and the "broken" flag remains on the item
[itens the armor station](http://prntscr.com/lhk66z)

[output and nbt](http://prntscr.com/lhk77f)
#### Expected Behavior:
"Broken" flag removed from the item, when getting the output

#### Steps to Reproduce:
1. break an item
2. put the item on an operational Energetic infuser with the flux reconstruction augment
3. take the "repaired" item
4. Try re-repair the item at the armor station

**Comment by TheIllusiveC4** [comment]
I'll look into this. One question, do Tinkers' tools show this behavior as well?

**Comment by Eldhelion** [comment]
I done some testing using wooden shovel
Like the armor, the durability is repaired on the machine, but the broken flag remains
[before repair](http://prntscr.com/li0aou)

[after repair](http://prntscr.com/li0bbn)

but unlike the armor, when trying to do the repair at the tool station, the output is without the flag, and the material is consumed, so the item is functional again.

[on tool station 1](http://prntscr.com/li06x7)
[on tool station 2](http://prntscr.com/li0bm6)

**Comment by TheIllusiveC4** [comment]
Alright thanks for the info, I'll try and figure out what's happening here.

**Comment by TheIllusiveC4** [comment]
It turned out to be a very easy fix. It won't fix the compatibility issue between the Energetic Infuser and Tinkers' armor/tools, but it will at least let you re-repair the armor in the Armor Forge to remove the Broken tag just like the tools.

**Comment by Eldhelion** [comment]
thanks
