### ISSUE TITLE
Armor doesn't fully render. 

### ISSUE THREAD

**Issue by HansTheSecond** [TheIllusiveC4/ConstructsArmory#136]
When putting the armor on it does not fully render, I have pictures.

#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.0.2

* Tinkers' Construct:1.12.2-2.11.0.106
* Mantle:1.12-1.3.3.39
* Forge:1.12.2

#### Observed Behavior:
Armor not fully rendering
#### Expected Behavior:
Fully rendered armor
#### Steps to Reproduce:
1. Creating armor
2.Changing skins
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by HansTheSecond** [comment]
![amore issue](https://user-images.githubusercontent.com/27984375/50321466-06afb380-049f-11e9-98d3-41f34615143b.PNG)

**Comment by HansTheSecond** [comment]
This is on a forge server, in addition this seems to apply to all the armor in the mod. Weapons from the tinkers mod are working fine though.

**Comment by TheIllusiveC4** [comment]
Please fill out the issue template, particularly the version numbers requested. That being said, can you reproduce this with only Tinkers' and Construct's Armory installed? If not, do you have any graphics mods installed that could have changed the rendering (Optifine, Mo' Bends, etc.)?

**Comment by HansTheSecond** [comment]
I do have optifine, i will attempt to remove them and see if that is the issue

**Comment by HansTheSecond** [comment]
Removed mo bends from server issue fixed, Thank you for fast response. Epic mods my friend!
