### ISSUE TITLE
Invisible Gui

### ISSUE THREAD

**Issue by Baggytrousers27** [TheIllusiveC4/ConstructsArmory#138]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.1
* Tinkers' Construct:1.12.2-2.11.0.106
* Mantle:1.12-1.3.3.39
* Forge:1.12.2-14.23.5.2768

#### Steps to Reproduce:
1. Have Lucraftcore and HeroesExpansion installed.
2. Load up new world
3. Interact with Armour station/forge
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
I wasn't able to reproduce this perfectly, but there are some weird GL issues going on here that I suspect come from Lucraftcore. It seems to be related to the player model preview. I'll try and see if there's anything I can do on my end, but in the meantime you can work around this by enabling the "Compact View" config option. This will disable the player model preview but it should at least grant you the basic functionality of the Armor Station/Forge.

**Comment by TheIllusiveC4** [comment]
It doesn't seem like Lucraftcore likes me rendering anything in the preview panel, so I think my hands are tied here unfortunately. You'll have to stick with the "Compact View" config option like I mentioned above if you want to play with these two mods together.
