### ISSUE TITLE
Wiki page doesn't include resources required to obtain modifiers, and some traits are missing

### ISSUE THREAD

**Issue by RainOfPain125** [TheIllusiveC4/ConstructsArmory#140]
I _suggest_ that it gets a little updating.

For instance, I have no idea how to get "Dexterous" because no items are given. Nor the one I actually want - "Speedy" (which I merely assumed was just sugar or something lol?)

I know there's the book in-game. And I respect if you only wanted people obtaining this info from the book itself.

**Comment by TheIllusiveC4** [comment]
Which traits are missing?

**Comment by RainOfPain125** [comment]
> Which traits are missing?

Assuming this isn't auto-generated or created by other mods in my modpack, but

Petramor, Direct, Crude, Vanishing, Unnatural, Twilit, Synergy, Flammable, Stalwart, so on.

**Comment by TheIllusiveC4** [comment]
They are indeed auto-generated and/or created by other mods. At least, all of those you listed anyways.

As for the modifier resources, I'll update them on the wiki page once I get a chance.

**Comment by TheIllusiveC4** [comment]
Wiki page has been updated with modifier resources.
