### ISSUE TITLE
[Suggestion]A way to toggle the modifiers on the boots, I put High stride, it does what I want, step assist, but in some situations, I would love to be able to toggle this on and off

### ISSUE THREAD

**Issue by mcdodge34** [TheIllusiveC4/ConstructsArmory#145]
This is a simple suggestion that could be very helpful, just a simple option to be able to turn on and off the high stride ability on the boots, I love the step assist much better than the vanilla one, but not all the times, especially when I'm building some parts of my base over the void and put some guard rails around and oops, the high stride makes me pass over the guard rails or walls like if there was nothing. I know by default this doesn't use durability and that's probably why it didn't occurs to you to make it toggle with a key press.

**Comment by TheIllusiveC4** [comment]
Due to the complexities of such a feature, I won't be adding toggleability to modifiers like High Stride. There's a reason only accessories can be toggled and even that is going to get phased out eventually.
