### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by AMartinie** [TheIllusiveC4/ConstructsArmory#150]
Mods are starting to implement radiation poisoning into their mods. Sources are typically ores. I know nuclearcraft implements radiation but I believe there are some others. I just wanted to suggest that a modifier to protect from radiation would be awesome, because otherwise we don't have a choice but to take off our Constructs armor and use something with radiation shielding.

**Comment by kierajreed** [comment]
Mod compatibility is the other mods' responsibility to implement, not this mod's.

**Comment by TheIllusiveC4** [comment]
In addition to what SkyHawkB said, it's just not really efficient for me to do it on my end. I have zero idea how radiation works, so the mods that are implementing that radiation are in a much better position to introduce compatibility than I am. Even more so if there are multiple mods doing this and I have no guarantees that one implementation would even work universally.
