### ISSUE TITLE
Cannot repair Construct’s Armory armour in Cyclic’s magma anvil

### ISSUE THREAD

**Issue by Dimentive** [TheIllusiveC4/ConstructsArmory#152]
When I put my Construct’s Armory helmet in the magma anvil, which repairs items using lava as fuel, from the mod [Cyclic](https://minecraft.curseforge.com/projects/cyclic), none of the helmet’s durability gets restored, and it goes straight into the right slot where fully repaired items go, even though it still has the same durability as it had when I put it in the magma anvil.

#### Steps to reproduce

1. Download [Tinkers’ Construct](https://minecraft.curseforge.com/projects/tinkers-construct), [Mantle](https://minecraft.curseforge.com/projects/mantle), [Construct’s Armory](https://minecraft.curseforge.com/projects/constructs-armory), and [Cyclic](https://minecraft.curseforge.com/projects/cyclic).
2. Put a piece of armour made in Construct’s Armory in Cyclic’s magma anvil and put lava in the anvil.

#### Versions
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579))
* **Minecraft:** 1.12.2 (duh)
* **Forge:** 14.23.5.2781
* **Construct’s Armory:** [1.2.3](https://minecraft.curseforge.com/projects/constructs-armory/files/2660796) (latest)
* **Tinkers’ Construct:** [2.12.0.135](https://minecraft.curseforge.com/projects/tinkers-construct/files/2693496) (latest)
* **Mantle:** [1.3.3.49](https://minecraft.curseforge.com/projects/mantle/files/2693483) (latest)
* **Cyclic:** [1.18.4](https://minecraft.curseforge.com/projects/cyclic/files/2688226)

**Comment by TheIllusiveC4** [comment]
Are you able to repair Tinkers' Construct tools with this method? Just making sure this isn't due to some inherited behavior.

**Comment by Dimentive** [comment]
Yes, I am.

**Comment by Dimentive** [comment]
Huh, I’m not able to repair Tinkers’ Construct tools and weapons in the magma anvil.

I thought that I could since I knew I could repair TiC tools and weapons in blocks that repair using energy, such as [Actually Additions’](https://minecraft.curseforge.com/projects/actually-additions) item repairer. It looks like neither Tinkers’ Construct tools and weapons nor Construct’s Armory armour can be repaired in Cyclic’s magma anvil. In that case, this is probably an issue on Cyclic’s side.

**Comment by TheIllusiveC4** [comment]
I'll close this issue for now then as a 3rd party resolution is required. Let me know if something else comes up and I'll re-open it.
