### ISSUE TITLE
Missing some localizations for armor accessories

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TheIllusiveC4/ConstructsArmory#153]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.3.1
* Tinkers' Construct: 1.12.2-2.12.0.115
* Mantle: 1.3.3.42
* Forge: 14.23.5.2768

#### Observed Behavior:
Travellers' Googles, Travellers' Cloak, Traveller's Knapsack and Traveller's Belt don't have their description on Armor Forge's GUI.

Unlocalized strings list
Travellers' Googles
`modifier.travel_googles_armor.desc`
`modifier.night_vision_armor.desc`
`modifier.soul_sight_armor.desc`
Travellers' Cloak
`modifier.travel_sneak_armor.desc`
`modifier.travel_slowfall_armor.desc`
Traveller's Knapsack
`modifier.travel_sack_armor.desc`
Traveller's Belt
`modifier.travel_belt_armor.desc`
`modifier.potion_belt_armor.desc`

#### Expected Behavior:
They are localized.
#### Steps to Reproduce:
Screenshot
![搜狗截图20190412135036](https://user-images.githubusercontent.com/37864486/56014961-f65f6500-5d29-11e9-9487-96059e2ca340.png)
#### Postscript:
If you fixed this bug, please let me update Chinese translation on my fork and create a pull request for you. Thanks!

**Comment by TheIllusiveC4** [comment]
I've added the missing entries, so you can go ahead and PR a Chinese localization update when you're ready.
