### ISSUE TITLE
[1.12.2] Intended to reach 100% Damage Reduction from Magic Damage Sources with Shielding Trait & enough Resistance Modifiers?

### ISSUE THREAD

**Issue by SonicX8000** [TheIllusiveC4/ConstructsArmory#154]
Unsure if this is intended but apparently with Shielding trait on all 4 armor pieces & about 30 Resistance Modifiers applied on the armor, you can reach 100% damage reduction vs Magic Damage Sources. Here's what I've done via testing.

Scaling Health's Debug Info was used to get my exact health value. Damage was not scaled at all.

-----

Armor used was Full Lead with the Shielding Trait. Shielding only applies once per Armor Piece meaning you just need 1 Lead Part and since magic damage ignores armor... Armor Points aren't listed here.

For this test I used '/summon minecraft:evocation_fangs' which summons the Envoker Fangs under you which bites you for 6 magic damage on Hard Mode if not wearing armor.

Damage Taken | My remaining health & Max - What I was wearing.

---

6.0 | 14.0 / 20.0 - Nothing
3.6 | 16.4 / 20.0 - Full Lead Armor with Shielding x4
2.64 | 17.36 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x1 (8)
1.7 | 18.32 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x2 (16)
0.72 | 19.28 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x3 (24)
0.6 | 19.4 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x3 + Resist I x1 (25)
0.48 | 19.52 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x3 + Resist II x1 (26)
0.24 | 19.76 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x3 + Resist IV x1 (28)
0.12 | 19.88 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x3 + Resist V x1 (29)
0.0 | 20.0 / 20.0 - Full Lead Armor with Shielding x4 + Resist VIII x3 + Resist VI x1 (30)

---

Using Full Manyullyn with different Shielding but with Max Resist.

2.16 | 17.84 / 20.0 - Full Manyullyn Armor + Resist VIII x4 (Total Resist: 32)
1.56 | 18.44 / 20.0 - Full Manyullyn Armor with Shielding Trim x1 + Resist VIII x4 (32)
0.960001 | 19.039999 / 20.0 - Full Manyullyn Armor with Shielding Trim x2 + Resist VIII x4 (32)
0.36 | 19.64 / 20.0 - Full Manyullyn Armor with Shielding Trim x3 + Resist VIII x4 (32)
0.0 | 20.0 / 20.0 - Full Manyullyn Armor with Shielding Trim x4 + Resist VIII x4 (32)

---

Unrelated but just for the heck of it since Scaling Health is added... let's scale up magic damage by 10000.0 with a weight of 0.1 and set my Scaling Health Difficulty to 1. This is how much damage I'll be taking by the fangs now...

"[Scaling Health]: magic on Zonic_Tonic: 6.0 -> 6006.0 (scale=10000.0, affected=0.1, change=6000.0)"

6006 total damage, and with 4x Shielding + 30 Resist Modifiers, that damage is still 0, however if I had 29 Resist Modifiers instead of 30, it deals 120.1196 damage after setting my health to 150.

I'm just wondering if it's intended to take 0 damage if you have a high enough Shielding & Resist modifiers.

**Comment by TheIllusiveC4** [comment]
> I'm just wondering if it's intended to take 0 damage if you have a high enough Shielding & Resist modifiers.

No. The intended cap is 80% damage reduction from magic.
