### ISSUE TITLE
Crash with Spiny trait on single player and Servers with explosions!

### ISSUE THREAD

**Issue by SirAron111** [TheIllusiveC4/ConstructsArmory#158]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.2.3.jar
* Tinkers' Construct:TConstruct-1.12.2-2.12.0.135.jar
* Mantle: Mantle-1.12-1.3.3.49.jar
* Forge:14.23.5.2822 higher or lower doesnt matter results the same

#### Observed Behavior:
Spiny Trait reacts badly with Explosions should only hit back on melee damage. (Was always strange when spiny hit back skeletons on range well must have been some long spikes)

#### Expected Behavior:
Not crashing?!

#### Steps to Reproduce:
1. Make an Armor with spiny
2. Best would be using grimoir of gaia as the goblins are your best bet for this behavior only got it once with a creeper and tnt before and didn’t think much of it
3. Spawn one that exploded (they are random could be archer could be melee could be exploder)
4. Have the exploder hit you in the armor should result in crash.

...

Crash Log: Here is the Crashlog:
https://pastebin.com/zAPxY9vN

**Comment by TheIllusiveC4** [comment]
I wasn't able to reproduce this, but I know what's going on and I've made some adjustments that should hopefully prevent the crashing.
