### ISSUE TITLE
Mod crash while server is starting

### ISSUE THREAD

**Issue by Twizt3r** [TheIllusiveC4/ConstructsArmory#159]
Don't know why it's crashing. Attaching crash report.

Thank you

[crash-2019-04-19_14.28.46-server.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/3098276/crash-2019-04-19_14.28.46-server.txt)

**Comment by TheIllusiveC4** [comment]
That's not my mod, that's [Armory Expansion](https://minecraft.curseforge.com/projects/armory-expansion).
