### ISSUE TITLE
Resource Pack / Custom Texture Rendering Issue

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/ConstructsArmory#160]
#### Versions
* Minecraft 1.12.2
* Construct's Armory: 1.2.3.3
* Tinkers' Construct: 2.12.0.135
* Mantle: 1.3.3.49
* Forge: 14.23.5.2836

#### Observed Behavior:
Custom model textures from a resource pack do not render correctly when supplied with a larger resolution than the stock Construct's Armory textures.

#### Expected Behavior:
Texture mapping onto Construct's Armory models should automatically scale to the source texture size when an alternate texture is provided by a resource pack.

#### Steps to Reproduce:
1. Set up conarm, tconstruct, mantle on a clean forge install
2. Activate a resource pack that contains textures for Construct's Armory in "assets/conarm/textures/models/armor/" at 2x original resolution.
3. Create a new Creative Mode game, spawn in some torso armor, and wear it
4. Observe the incorrect rendering in-inventory and in-world
5. Disable the resource pack and observe the rendering return to normal.

I have included my test pack as an attachment -- these textures were generated by a simple scale and median blur with GIMP so they don't look great; I was planning on making a Faithful32-style pack for Construct's Armory but I don't want to invest a bunch of time making these look good unless the bug is possible to fix.

I'm loving the mod btw, I have a small personal server i run for friends with a custom mod pack and this addition has been very well received. Good balance and a great compliment to Tinker's. Keep up the great work :D

EDIT:
1. fixed the zip file upload. I put it together with the wrong folder structure from my test folder. whoops.
2. Forgot to mention that it's just the models that seem broken; all the inventory items and parts seem to render fine.

[conarm-32-test.zip](https://github.com/TheIllusiveC4/ConstructsArmory/files/3100865/conarm-32-test.zip)

![front](https://user-images.githubusercontent.com/11343812/56464927-63719b00-63b9-11e9-81e8-208a7781b38a.jpg)
![back](https://user-images.githubusercontent.com/11343812/56464930-666c8b80-63b9-11e9-8a1c-291229cef56e.jpg)
![inventory](https://user-images.githubusercontent.com/11343812/56464932-6bc9d600-63b9-11e9-85de-d765c5df122a.jpg)
![modmenu](https://user-images.githubusercontent.com/11343812/56464934-708e8a00-63b9-11e9-9511-5413be7e6ae7.jpg)

**Comment by TheIllusiveC4** [comment]
Thanks for the comprehensive bug report, I'll get back to you ASAP about whether it's possible to fix this.

**Comment by TheIllusiveC4** [comment]
Surprisingly simple fix, will be released shortly.

![2019-04-21_00 52 49](https://user-images.githubusercontent.com/29991504/56467143-e7368200-63cf-11e9-8306-6050ff9ac434.png)

**Comment by ghost** [comment]
Holy crap thanks for the speedy response! Time to get to work on some textures :)

**Comment by thecrescentkid** [comment]
I'm having the same problem in the latest version of the mod 1.12.2-1.2.4
