### ISSUE TITLE
problems with harvest tweaks when using this mod and metallurgy_reforged

### ISSUE THREAD

**Issue by cosmo3001** [TheIllusiveC4/ConstructsArmory#161]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.2.3.4.jar 
* Tinkers' Construct: TConstruct-1.12.2-2.12.0.135.jar
* Mantle:	Mantle-1.12-1.3.3.49.jar
* Forge: minecraft forge 14.23.5.2835

added mods
HarvestTweaks-1.12-0.1.6.jar
Metallurgy-4-Reforged-0.2.0

#### Observed Behavior:
harvest tweaks make a config with all tinker material so i can set harvest level of the tools and it includes all materials from tinker / vanilla / metallurgy.

when using Construct's armor all metallurgy materials get removed from the tinker tool list in harvest tweak.
#### Expected Behavior:
not to affect harvest tweaks at all and leave metallurgy alone :)

#### Steps to Reproduce:
1.install the above mods 
2.run client 1 time to get all the config
3.look in harvest tweak config "TinkersConstruct.cfg"
4 if no metallurgy materials is in the list remove mod construct's armory and delete harvest tweaks config 
5, reload the game without construct's armory and this time the TinkersConstruct.cfg in harvest tweaks will have all the metallurgy materials on the list
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
This is not a Construct's Armory issue, this is a Harvest Tweaks issue related to loading order. It looks like they have already fixed it in their GitHub repo but haven't released a new build with that change. Regardless, it's out of my hands.

**Comment by cosmo3001** [comment]
thanks for taking the time to find out :)
