### ISSUE TITLE
Incompatibiliti

### ISSUE THREAD

**Issue by Elthagrim** [TheIllusiveC4/ConstructsArmory#163]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.3.4
* Tinkers' Construct: TConstruct-1.12.2-2.12.0.135
* Mantle: Mantle-1.12-1.3.3.49.
* Forge: 14.23.5.2836
* Tinkers Defense: tinkersdefense-1.4.2.25.1

#### Observed Behavior:

Conarm causes incompatibiliti with tinkers defense. (or viceversa)

[crash-2019-04-27_23.30.33-client.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/3124395/crash-2019-04-27_23.30.33-client.txt)

**Comment by TheIllusiveC4** [comment]
I believe Tinkers' Defense/Compendium has fixed this in their 1.4.2.26.1 version.

**Comment by Elthagrim** [comment]
Its fixed.
