### ISSUE TITLE
freezing bug

### ISSUE THREAD

**Issue by Late-Night** [TheIllusiveC4/ConstructsArmory#166]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.3.1
* Tinkers' Construct: 2.12..0.135
* Mantle: 1.3.3.49
* Forge: 14.23.5.2768

#### Expected Behavior: should be obvious

*note: the problem may be on metallurgy 4's side, and the devs are working to fix the issue if it's their side. i just want to be sure if it's this mod's fault, or if it's metallurgy's

#### Steps to Reproduce:
1.make armor with more than one material/trait
2.attempt to equip it(both ways cause the freeze, i and some others tested both ways)
3.
...

Crash Log: not a crash, so no log

**Comment by TheIllusiveC4** [comment]
Fairly sure it's a Metallurgy issue. I'm not entirely sure what's going on, but this issue only occurs when Metallurgy is present and I haven't been given any evidence from the people who have reported this issue before to believe it's an innate Construct's Armory issue.

**Comment by Late-Night** [comment]
apologies, the metallurgy devs say it _is_ their side. i didn't know

**Comment by HurtsAsHell** [comment]
Sorry, he didn't realize we had warned that the problem was ours. We solved it anyway
