### ISSUE TITLE
[Suggestion] Disabling armor materials

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/ConstructsArmory#168]
#### Suggestion Description:
The ability to disable armor materials would be useful for balancing and pack development, whether it be through extending CraftTweaker integration capabilities, or through a blacklist located in the config.

Having this capability on Construct's Armory's end would provide the capability to disable any materials integrated by vanilla, tconstruct, or any other mods for balancing purposes or if the material is just still in a WIP state etc.

**Comment by paulgb434** [comment]
You could also use Tinkers Extras to disable materials as well as Armor Parts made of specified materials.
