### ISSUE TITLE
Creative modifier and tinker tool leveling support

### ISSUE THREAD

**Issue by Pabilo8** [TheIllusiveC4/ConstructsArmory#17]
It would be nice to have that,I really like your mod. Also, could you add shields?

**Comment by TheIllusiveC4** [comment]
1. Creative modifier should already be in the latest update. It's the same material as the creative modifier for tools.

2. Tinker Tool Leveling support is planned, but it probably won't be implemented until this mod is out of alpha.

3. I will not add shields. Shields are more like tools than armor. I think the Battlesigns from Tinkers' Construct do a fine job of filling that niche as it is.
