### ISSUE TITLE
Fall Damage Bug

### ISSUE THREAD

**Issue by misterYeet823** [TheIllusiveC4/ConstructsArmory#174]
#### Versions (Be specific, do not write "latest"):
* Sky Factory 4: 4.0.8
* Construct's Armory:  1.12.2-1.2.3
* Tinkers' Construct: 1.12.2-2.12.0.135
* Mantle : 1.12- 1.3.3.49
* Forge: 1.12.2-14.23.5.2838
#### Observed Behavior:
while the slow fall on chestpices turned on, dosnt take fall damage, but brings the fall damage to the next time taking fall damage
(lets say jumping off from 40 blocks high, when slow fall is activated, does not take damage at all (which is normal) but when taking fall damage after the first jump (eg. 5 blocks which does half a heart of damage) takes full damage from the first jump instead while slow fall is deactivated.
#### Expected Behavior:
should be ignoring the first fall damage since slow fall is on
taking normal fall damage on second drop when slow fall is off instead of taking the fall damage from the first drop.
#### Steps to Reproduce:
1. drop from a high place with slow fall on
2. turn off slow fall
3. drop from any height that is not higher then the first drop
4. takes the fall damage from the first drop even its a 4~5 block height.

**Comment by misterYeet823** [comment]
Forgot about the Mantle Version
Mantle Version: 1.12- 1.3.3.49

**Comment by TheIllusiveC4** [comment]
Sorry it took so long to get to this.

I'm sorry but I can't reproduce this. No matter how many times I fall from a large height (50+ blocks) with slow fall, turn it off, and fall again (4-10 blocks), the second fall always deals the appropriate amount of damage (very small). Also, nothing in the code for the slow falling should be able to even propagate to the next fall. 

Can you reproduce this with just Construct's Armory and dependencies?

**Comment by TheIllusiveC4** [comment]
Closing this for now due to inability to reproduce and lack of response. If anyone has additional information to offer that suggests this is still a valid issue, I'll be happy to re-open it then.
