### ISSUE TITLE
[Suggestion] Configurable XP Gain/Cap for Armor. *Unsure if this belongs here.*

### ISSUE THREAD

**Issue by SonicX8000** [TheIllusiveC4/ConstructsArmory#176]
Unsure if this belongs here unless this is mainly related to Tinkers Tool Leveling but in the config there's a 'levels' section so figure I give it a post here.

Using this mod alongside Scaling Health where you can have the damage taken scaled depending on the difficulty... I noticed that the XP cap is 100 despite surviving a 5000 damage attack due to certain defense factors.

An example upon touching some spikes from Extra Ultilties 2 wearing a Manyullyn Chestplate with Colbat Plates & lead Trim. (+8 Armor, 0 Toughness.). It's XP is 100/320.

 spike on Zonic_Tonic: 4.0 -> 404.0 (scale=2.0, affected=50.0, change=400.0)

Armor gains only 100 XP, meaning that 304 of the XP was lost. I had 1000 health for testing purposes and I am left with 622/1000 health, actual damage taken was 378 with 26 damage reduced due to having 8 armor but the XP gain appears to be based on the base damage taken.

I was wondering if either the XP cap could be configurable so one can cap it at say... 500 XP or some kind of configurable XP Gain Multiplier where if it was set at "0.5" you'll only gain half the amount of XP from the base damage. Here are some examples.

Example 1
Damage taken is 100, XP Gain Multiplier is set at "0.5". Only 50 XP is gained for your Armor.

Example 2
Damage taken is 300, XP Gain Multiplier is set at "0.5". You should get 150 XP but due to the cap being at 100... only 100 XP is gained while 50 of the XP is lost.

Just figure it would allow one to fine-tune the XP amounts for certain... purposes, like an RPG of some sorts.

The defaults for the configs would be...

XP Cap: 100 | XP Gain Multiplier: 1.0

**Comment by YaibaToKen** [comment]
possibly a way to fine-tune how damage translates to XP gained with mathematical formulas
