### ISSUE TITLE
NoSuchFieldError crash during init with potential upcoming TiC version

### ISSUE THREAD

**Issue by tomdodd4598** [TheIllusiveC4/ConstructsArmory#178]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.4
* Tinkers' Construct: 1.12.2-2.12.0.161
* Mantle: 1.12-1.3.3.55
* Forge: 14.23.5.2838
#### Steps to Reproduce:
1. Load the game, wait for init stage (3/7)

Crash Log: https://pastebin.com/7tcBdnTd

This version of TiC is not yet available, but I thought it would be worth passing this on in case you hadn't already seen it: recently there was [a PR](https://github.com/SlimeKnights/TinkersConstruct/issues/3910) made to split the 'listAllMaterials' TiC config into separate booleans for tools and parts. This of course causes a NoSuchFieldError.

**Comment by TheIllusiveC4** [comment]
Hm, okay, good to know. Thanks for the heads up.

**Comment by SonicX8000** [comment]
Tinkers Constructed released the update.

TConstruct-1.12.2-2.13.0.171

...and thus, crashes upon load.
https://pastebin.com/LBFSS9W8
