### ISSUE TITLE
1.12.2 applying Armor Kits makes armor visuals disappear

### ISSUE THREAD

**Issue by Zygus42** [TheIllusiveC4/ConstructsArmory#18]
TConstruct-1.12.2-2.9.1.65
conarm-1.12.2-0.0.8-a

Applied Speedy armor kit to knight slime helmet, and it no longer has an appearance.
Applied Diamond armor kit to chest and it no longer has an appearance AND the knight slime legs and boots also can not be seen any more, even though they have no armor kits on them.

![2018-03-16_11 45 13](https://user-images.githubusercontent.com/20757445/37502894-56b0cb82-2910-11e8-8393-5ae33aad6857.png)
![2018-03-16_11 50 22](https://user-images.githubusercontent.com/20757445/37502896-598a3014-2910-11e8-8951-91e10d0e3d55.png)
![2018-03-16_11 50 25](https://user-images.githubusercontent.com/20757445/37502899-5ed41a62-2910-11e8-8f81-bcef50d3b496.png)

**Comment by TheIllusiveC4** [comment]
That's super weird, I've never encountered anything like this. Can you replicate this behavior with just TConstruct and ConArm installed?

**Comment by Zygus42** [comment]
When I logged out and back in, all my armor is visible again.  I'll try that test shortly.

**Comment by Zygus42** [comment]
You are correct - was fine with just your mod on.  After some more investigation, seems to be a conflict with TexFix.  I will let them know.

**Comment by TheIllusiveC4** [comment]
Alright, cool.
