### ISSUE TITLE
Game crashes when equipping certain armours 

### ISSUE THREAD

**Issue by Toraden** [TheIllusiveC4/ConstructsArmory#180]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.3.4
* Tinkers' Construct: 1.12.2-2.12.0.123
* Mantle: 1.3.3.42
* Forge: 14.23.5.2838
* Baubles: 1.12 - 1.5.2
* Buildcraft: 7.99.23
* Just Enough Items: 4.15.0.268
* Extra Utilities 2
*  Metallurgy 4: Reforged: 0.2.0
* Refined Storage: 1.6.15
* RF Tools: 1.12-7.72
#### Observed Behavior:
When attempting to equip certain armour pieces with embossments or travellers gear the game freezes, examples found to cause the freeze:

Osmium Helmet + Travellers Goggles (Soul Sight) + jump Boost + Resistance IV + Speedier (+10%)

Tartarite Helmet [Tartarite + Osmium + Paper] + Writable + Diamond + Emerald + Resistant + Resistance IV Embossment (Celengil) + Speedy

Tartarite Boots + Writable + Speedier + Resistant + Jump Boost Embossment (Astral Silver)

The freeze DOES NOT occur if you do not include the emobssment, example:

Tartarite Helmet [Tartarite + Osmium + Paper] + Writable + Diamond + Emerald + Resistant + Speedy

#### Expected Behavior:

Armour should become equipped as normal

#### Steps to Reproduce:
1. Create armour from Constructs with Embossment or Travellers Gear
2. Attempt to equip armour piece

**Comment by TheIllusiveC4** [comment]
This is a known issue with Metallurgy 4: Reforged compatibility. Please update your Metallurgy 4 version (latest is 0.2.2) and refer this issue to those developers if it's still present in the latest version.

**Comment by Toraden** [comment]
@TheIllusiveC4 Thanks, about 20 minutes after posting I realised this was probably the case.
