### ISSUE TITLE
Traveller's Belt: Storage (Leggings upgrade) doesn't respond to hotkey

### ISSUE THREAD

**Issue by katubug** [TheIllusiveC4/ConstructsArmory#182]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.2.4
* Tinkers' Construct: TConstruct-1.12.2-2.12.0.157
* Mantle: Mantle-1.12-1.3.3.55
* Forge: forge-1.12.2-14.23.5.2846-universal

#### Observed Behavior:
The "Traveller's Belt (Storage)" upgrade cannot be accessed via hotkey, either default or reassigned. The "Traveller's Belt (Alchemy)" and "Traveller's Knapsack" chestplate accessory both function just fine.

#### Expected Behavior:
I expect the Belt to open an inventory window, similar to the one from the Alchemy Belt.

#### Steps to Reproduce:
1. Using just ConArm and required dependencies (also JEI), craft/give any type of ConArm leggings.
2. Upgrade the leggings with the "Traveller's Belt (Storage)."
3. Equip the leggings.
4. Attempt to use hotkey.

I'm not sure if this is a bug or if I'm just expecting the wrong behavior. I have tested it both with mixed-material leggings and ones I just cheated in from JEI. The issue seems to persist despite the different materials.

**Comment by TheIllusiveC4** [comment]
The Traveller's Belt (Storage) does not open an inventory window. It swaps your hotbar with an internal hotbar storage inside of the belt. So it's basically like having two hotbars. Test that out and see if that's functioning correctly.

**Comment by katubug** [comment]
Derp! Yes, that works perfectly. My apologies for the mistake!
