### ISSUE TITLE
[Bug]broken textures and models?

### ISSUE THREAD

**Issue by thecrescentkid** [TheIllusiveC4/ConstructsArmory#184]
cosmic armor breaks 3d

![2019-10-03_04 34 55](https://user-images.githubusercontent.com/37762002/66115885-575c4d00-e597-11e9-80d1-f63f61619b80.png)

**Comment by TheIllusiveC4** [comment]
Please fill out the issue template. I need at least all of the relevant version numbers. Also, can you replicate this without any other mods?
