### ISSUE TITLE
Model improvment

### ISSUE THREAD

**Issue by thecrescentkid** [TheIllusiveC4/ConstructsArmory#186]
![2019-10-03_04 34 55](https://user-images.githubusercontent.com/37762002/66182792-0a7e8200-e63c-11e9-85a1-da20a26d65d1.png)
I would like this mod to have compatibility with 
Vic modern warfare 2.0 mod, 
because right now it just bugs the armor.

**Comment by TheIllusiveC4** [comment]
Can you reproduce this without Vic's Modern Warfare? Because if you can't, then this is something you will have to bring up with the Vic's Modern Warfare developer. I don't do anything particularly special with the armor models to warrant "improving" them.
