### ISSUE TITLE
Armor does not scale with player when used with More Player Models

### ISSUE THREAD

**Issue by OneTwoMint** [TheIllusiveC4/ConstructsArmory#187]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.4
* Tinkers' Construct: 1.12.2-2.12.0.157
* Mantle: 1.12-1.3.3.55
* Forge:  1.12.2-14.23.5.2838
* More Player Models: 1.12.2-(29Sep19)
#### Steps to Reproduce:
1. Install More Player Models.
2. Put on any Construct's Armory armor.
3. Go into the character screen by either its tab in the survival inventory or by the keybind- F12 is the default.
4. Either edit an existing preset or create a new preset.
5. Go into the "Scale" menu. Select a part and change the scale of it- It's most noticeable when you change the height of the body and the legs.
6. Observe mismatch between player body and armor.

Crash Log: N/A. Game is playable despite the incompatibility.

**Comment by TheIllusiveC4** [comment]
Does the scaling feature work with armor sets from other mods? If they do, can you name them?

**Comment by OneTwoMint** [comment]
Yes. It works with Traveller's Backpacks, and armors from Tiny Progressions, Tech Reborn, Base Metals, Industrialcraft2, Actually Additions, Redstone Arsenal, Galacticraft, Cyclic, Immersive Engineering, Mystical Agriculture, Thermal Foundation, and Ender IO, and most armors from Mekanism: Tools, with the exception of the glowstone armor set from Mekanism: Tools. 

The mods I play with that have armors that don't work with MPM besides Construct's Armory are Botania, Draconic Evolution, and Thaumcraft (Save for Thaumium and Void sets). 

If it means anything, I tested mostly just the helmets from each of the listed mods (Exception being Traveller's Backpacks, since that's not properly armor but it's close enough). I tested a couple matching chestplates, and effectiveness did seem consistent between helmets and chestplates, so I'm making the assumption that that is enough.

**Comment by TheIllusiveC4** [comment]
Okay, from what I can tell (and feel free to contest), it seems like the scaling feature from MPM doesn't work with non-vanilla armor models. All of the ones you listed that work are only using the vanilla armor models (with different textures), and the ones that don't work are using custom armor models. If that's the case, this is a problem for the MPM developer to solve as there would be little I can do on my end to fix this.
