### ISSUE TITLE
[bug]compatibility issues with vic modern warfare and constructs armory.

### ISSUE THREAD

**Issue by thecrescentkid** [TheIllusiveC4/ConstructsArmory#188]
I know now though testing it,s caused by VIC,s modern warfare, I think the mod does some the to the player model to improve the reload animations, and that breaks armor mods like constructs armory.

#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.4
* Tinkers' Construct: 1.12.2-2.12.0.157
* Mantle: 1.12-1.3.3.55
* Forge: 14.23.5.2847
* Modern warfare: MW 2.0 Contagion v0.4.1 mc1.12.2

**Comment by TheIllusiveC4** [comment]
This is the fifth issue you've opened about the same topic. Please do not spam the repository with duplicate issues. I've already replied to your issue twice. If this is caused by Vic's Modern Warfare, then you need to report this issue to that developer.
