### ISSUE TITLE
doesn't work (for the most part)

### ISSUE THREAD

**Issue by GameRZ55** [TheIllusiveC4/ConstructsArmory#190]
#### Notice
i am trying to use constructs armory for my modded server and when i try to use constructs armory my game crashes, i tried with a couple different versions of the mod but to no avail. then i tried to use the "sources" version of the mod and to my surprise it worked, but it is incompatible with the one installed in my aternos server and i cant install this version in my aternos mod list, so I'm left with no options other than just wait for a response here

#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.4
* Tinkers' Construct:1.12.2-2.12.0.157
* Mantle:-1.12-1.3.3.55
* Forge:1.12.2-14.23.5.2768
#### Steps to Reproduce: 
1. put the mod in my mods folder along my other mods
2. run minecraft
3. minecraft crashes

Crash Log: https://paste.dimdev.org/lezezehami.mccrash

**Comment by TheIllusiveC4** [comment]
I believe this is fixed in Tinkers' Compendium 1.4.2.29.3 (you have 1.4.2.29.2).
