### ISSUE TITLE
Removing accessories for upgrading?

### ISSUE THREAD

**Issue by jarquafelmu** [TheIllusiveC4/ConstructsArmory#191]
**Please describe the new feature or change.**
I haven't seen the ability yet or seen it talked about but it would be really nice to be able to change out the accessories attached to an armor piece. Like if I initially put just the zoom goggles on the head and later i want the night vision ones it would be nice to be able to just swap them out or do a destructive trade in where adding a new accessory overwrites an existing one.

**Please describe why you want this feature.**
Having spent a lot of time getting a piece of armor up to a good experience quality it is a shame to have to create a whole new piece at beginning quality because I now can craft the night vision or soul vision but can't because I don't want to have start all over with a new helmet.

**Comment by TheIllusiveC4** [comment]
This is something that I'll need to look over when I do the rewrite, but for the current version of Construct's Armory this won't be added. Accessories are meant to act like modifiers, which can't be overridden or replaced.
