### ISSUE TITLE
Crash 1.12.2 after phase 5 loading 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheIllusiveC4/ConstructsArmory#192]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.2.5.jar from conarm-1.12.2-1.2.4.jar
* Tinkers' Construct: TConstruct-1.12.2-2.13.0.171.jar from TConstruct-1.12.2-2.12.0.157.jar
* Mantle: Mantle-1.12-1.3.3.55.jar
* Forge: 14.23.5.2847
#### Observed Behavior:
Crash Log - https://gist.github.com/P3rf3ctXZer0/6b323af6f0807c7ea93128e20eea47b8
#### Expected Behavior:
No crash
#### Steps to Reproduce:
1. Update my pack from 0007 to 0008
2. 
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

::Notes::
I am not confident I need to deconstruct my pack because it worked just fine before I updated but I have to say that I did update 4 other mods including 

foamfix foamfix-0.10.8-1.12.2.jar from foamfix-0.10.7-1.12.2.jar
jeid JustEnoughIDs-1.0.3-48.jar from JustEnoughIDs-1.0.3-44.jar

**Comment by P3rf3ctXZer0** [comment]
Don't close cause I am going to try and find the error point.

**Comment by P3rf3ctXZer0** [comment]
So yeah I managed to cause this with just updating tinkers construct and conarmory

**Comment by P3rf3ctXZer0** [comment]
Nevermind I lied

**Comment by P3rf3ctXZer0** [comment]
Still investigating

**Comment by TheIllusiveC4** [comment]
It's Tinkers' Defense/Tinkers' Compendium causing the crash. Remove the mod and it should work.

**Comment by P3rf3ctXZer0** [comment]
So please reopen the issue as that mod is not in my current test environment

**Comment by P3rf3ctXZer0** [comment]
nevermind keep it closed
