### ISSUE TITLE
Question: How is durability calculated?

### ISSUE THREAD

**Issue by joelou1** [TheIllusiveC4/ConstructsArmory#195]
I know this ain't a bug report or a suggestion. I am trying to modify some armor's stats to fit my needs on my personal modpack because I find some armor too OP (Using mods that add material and allow stat modifications.) But no matter how I try, I can't seem to find the exact calculation for an Armor's Durability. I just want to avoid having armors with 100k dura. So what is the formula?

**Comment by TheIllusiveC4** [comment]
There are different durability multipliers for each armor type. It's 13, 15, 16, and 11 for boots, leggings, chestplates, and helmets respectively.

Taking the `Multiplier` as a variable, the formula is `((Core Durability + Trim Durability) * Multiplier * Plating Modifier + (Plating Durability * Multiplier))`.

**Comment by joelou1** [comment]
I see... I've been looking through the source code forever to find this information... I was missing the multiplier for the armor type. I owe you one! Thanks a bunch! I'll be able to start nerfing some materials!
