### ISSUE TITLE
[1.2.5.2] Any broken block drops XP

### ISSUE THREAD

**Issue by ACGaming** [TheIllusiveC4/ConstructsArmory#196]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.2
* Tinkers' Construct: 2.13.0.171
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Observed Behavior:
Any broken block drops XP.
This issue is very likely associated with the recent change of the 'Ambitious' trait.
#### Expected Behavior:
Only certain blocks drop XP by default.

**Comment by touhouzun** [comment]
Yeah, those XPs are FAKE orbs. They don't fulfill the experience bar, really?
