### ISSUE TITLE
Crash with Hammer Core

### ISSUE THREAD

**Issue by ym1025** [TheIllusiveC4/ConstructsArmory#197]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory:1.12.2-1.2.5.3
* Tinkers' Construct:1.12.2-2.13.0.171
* Mantle:1.3.3.55
* Forge:1.12.2-14.23.5.2847
*Hammer Core:2.0.5.6
#### Observed Behavior:
I tried to use Armor Station,Minacraft has crashed.
#### Expected Behavior:
Open ConArm's Armor Station's GUI
#### Steps to Reproduce:
1.Right click to armor station
2.
3.
...

Crash Log: [pastebin](https://pastebin.com/CRwf7E5X).

**Comment by TheIllusiveC4** [comment]
The crash is from Hammer Core so it'll need to be fixed on their end.
