### ISSUE TITLE
[Feature, Future] Armor Station

### ISSUE THREAD

**Issue by ElvenChaos** [TheIllusiveC4/ConstructsArmory#2]
Eventually, this mod should include an armor station similar to TCon's tool station.

Purpose: Allow early access to the mod's functions, limited to a "weaker" set until the station is upgraded to a forge. Early access to armors is an important function for pack makers who may want to use this mod to substitute for vanilla-style armors. It also allows for a sense of gradual progression and learning as the "core" of the features is used first, then is expanded to greater complexity and power.

Implementation: The same implementation used by TCon doesn't actually make sense here. You can't gate certain parts to just the forge, because each piece uses all of the same part-types. Instead, there are two options as things are:

1. You can gate certain material types (defined by a configurable list). A list of materials could narrow down armor choices to "early-game" armors like wood, flint, stone, or other natural and easily attainable materials, until the armor forge is available. This method would make the forge essential for getting to a defined tier of armors and important for player power progression.

2. You could force all armor pieces to be made of single-material types. For example, if I wanted to make a copper helmet in a station instead of a forge, I would have to make all three pieces (core, plates, trim) of copper. This method gates some of the trait complexity _(4 armor pieces with 3 ingredients/traits per piece for 12 potential unique traits in forge, or 4 armor pieces with 1 ingredients/traits each for 4 potential unique traits in station)_ and power, making the steps from station to forge more natural and rewarding. _This is my favorite choice due to its similarity to how the TCon tool forge feels -- it is less forced and necessary but still highly desirable due to the increase of potential options on upgrade._

EDIT: I meant traits, not modifiers. Woops.

**Comment by TheIllusiveC4** [comment]
You're correct in that the same implementation as TCon wouldn't apply, which is why I avoided adding in an equivalent for the moment. However, I do agree that an early-tier alternative is highly desirable and I like both your suggestions. I'm definitely going to add something like this in eventually.

**Comment by TheIllusiveC4** [comment]
I ended up going with implementation 2.
