### ISSUE TITLE
Visual Bug with Armor Forge

### ISSUE THREAD

**Issue by am-Andu** [TheIllusiveC4/ConstructsArmory#201]
I recently made a modpack in which I'm running the most recent version of Construct's Armory (1.12.2-1.2.5.3) and Tinker's Construct(1.12.2-2.13.0.171), as well as PlusTiC, Armory Expansion, and Tinker's Compendium (though I had this issue without Compendium), and I have an issue where the buttons in the Armor Forge are functional but invisible, as seen in the picture below.
<img width="834" alt="Capture" src="https://user-images.githubusercontent.com/59677298/72036955-79d2c600-326a-11ea-93fd-c272217bd919.PNG">
I don't have any mods that majorly alter my hud or Tinker's in general that I haven't used before in other packs, and I haven't had this issue in those other packs.  My modlist is [here](https://pastebin.com/Um2G1tSz) if you need it.

**Comment by TheIllusiveC4** [comment]
I don't see anything in your modlist that stands out to me as potentially incompatible. Does this visual glitch occur if you run only Construct's Armory and its dependencies? If not, then you'll need to figure out which mod in particular is causing the issue before I can look into it. In the meantime, you could try and activate the Compact GUI config option to see if that at least gives you functionality back.
