### ISSUE TITLE
Unlimited Modifiers on unbreakable armour

### ISSUE THREAD

**Issue by Frandana** [TheIllusiveC4/ConstructsArmory#206]
* Construct's Armory:  1.12.2 - 1.5.2
* Tinkers' Construct: 1.12.2 - 2.13.0.171
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847

**Observed Behaviour**

Adding a new modifier to an **unbreakable** armour piece does not reduce the amount of modifiers remaining on it, meaning you can add as many as you want without needing to level the armour.

**Expected Behavior:**

When adding a modifier to a chestplate I would expect the tooltip to show the "Modifiers remaining" number to go from 1 to 0

**Steps to Reproduce:**

1. Make armour with manyullyn main part and steel armour plates and trim. 

2. Add 5 x reinforcement modifiers until the armour is unbreakable.

3.  Add further modifiers, (I was adding resistance) watch the 'Modifiers' number in the tooltip (hold shift over the armour piece). It doesn't go down. You can add as many modifiers as you want.

_Let me know if you need more info._

**Comment by TheIllusiveC4** [comment]
I'll need some more specifics since things seem to work fine on my end. Have you tried this with other modifiers? Because your specific example, the Resistance modifier, only requires one modifier slot across multiple levels. You can bring it up to Resistance VIII using only a single modifier, so you won't see it go down if that's your only example.

**Comment by Frandana** [comment]
Ah I see. I wasn't aware that the resistance modifiers only require one modifier slot across multiple levels. I thought it would have been more in line with, say, mending moss where one level costs one modifier point. As it stands now getting up to Resistance VIII using only a single modifier seems extremely OP!!
Anyway i've closed the ticket. 

Keep up the good work!
