### ISSUE TITLE
Conflict with Obfuscate mods

### ISSUE THREAD

**Issue by DerRoboMeister** [TheIllusiveC4/ConstructsArmory#209]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.3
* Tinkers' Construct: 2.13.0.179
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Steps to Reproduce:
1. Equip armor (preferably something like the chestplate)
2. Hold an item that uses Obfuscate's animation library
3. Enter third-person

![2020-02-16_11 32 27](https://user-images.githubusercontent.com/23659870/74608559-12e9cd80-50b0-11ea-84a5-7a47375afd67.png)

**Comment by DerRoboMeister** [comment]
I meant to add the mod conflict tag, sorry..

**Comment by TheIllusiveC4** [comment]
This is likely not something fixable on my end, and it seems that the overall issue is unrelated to Construct's Armory from what I can tell by the issues on Obfuscate's project page.
