### ISSUE TITLE
Wither Effect crashes/kicks players with Manyullyn Armor

### ISSUE THREAD

**Issue by BrendanatorX** [TheIllusiveC4/ConstructsArmory#21]
Have noticed that the Manyullyn Armor from here causes the wither effect to instantly crash players, am using this on the NFINITE skyblock modpack/server, and tested with multiple people, and with a different armor and with flint armor, could get the wither effect, but did not crash, and with no armor, got wither effect and did not crash, but with Manyullyn, likely because of it's resistance to magical effects trait, Wither causes an exception/crash thingo..

**Comment by kierajreed** [comment]
It could be another weird mod compatibility issue. Can you replicate this bug using only TiCon and ConArm (use Mantle and the latest ConArm)?

**Comment by TheIllusiveC4** [comment]
I cannot replicate this behavior. In addition to what SkyHawkB said, can you post the crash log? The curious part is that Prideful does not have any special behavior between potion types. So if you're crashing because of Wither, you should theoretically be crashing from ANY potion effect.

**Comment by BrendanatorX** [comment]
Also managed to get a crash from putting my armor on.. I have the same materials/traits/modifiers for each piece. Manyullyn Core/Plates and Bone Trim
![image](https://user-images.githubusercontent.com/26519206/37576185-39567188-2b7f-11e8-8741-79725574b330.png)

**Comment by BrendanatorX** [comment]
Haven't managed to set up a stress test without all the other mods and things in the modpack yet though..

**Comment by TheIllusiveC4** [comment]
Please get back to me once you can provide the information requested above.

**Comment by TheIllusiveC4** [comment]
Any update on this?

**Comment by BrendanatorX** [comment]
Gosh, so sorry.
I've tested this now with only tinker related mods, the same forge version and mc version, and it has no problems, which means it's a mod conflict with.. something.. but I'm not sure what..

**Comment by BrendanatorX** [comment]
Am about to run another singleplayer test with everything like before but grab the crash log if possible for you

**Comment by BrendanatorX** [comment]
Okay, whatever the issue is now, mods have been updated, and the issue no longer occurs..

**Comment by TheIllusiveC4** [comment]
Very odd. Well, as long as it's gone I suppose. I'll close this issue for now. If it crops up again, just grab the crash log and comment again so I can reopen it.
