### ISSUE TITLE
Table not working

### ISSUE THREAD

**Issue by orionplay** [TheIllusiveC4/ConstructsArmory#210]
![image](https://user-images.githubusercontent.com/61280583/74939001-dc70c300-53cd-11ea-836d-26ecfc1580f7.png)

**Comment by TheIllusiveC4** [comment]
Likely a duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/201, and as I've asked there:

> Does this visual glitch occur if you run only Construct's Armory and its dependencies? If not, then you'll need to figure out which mod in particular is causing the issue before I can look into it. In the meantime, you could try and activate the Compact GUI config option to see if that at least gives you functionality back.
