### ISSUE TITLE
Embossing Accepts Incorrect Armor Cores

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/ConstructsArmory#211]
#### Versions:
* Construct's Armory: 1.12.2-1.2.5.4
* Tinkers' Construct: 1.12.2-2.13.0.179
* Mantle: 1.3.3.55
* Forge: 1.12.2-14.23.5.2847-universal

#### Observed Behavior:
With all tested materials so far, I can reliably emboss using the "wrong" armor core, i.e. a manyullyn helmet core can be used to emboss the vengeful trait onto cobalt leg armor. This allows for "cheap" embossing, since you can just use  which allows for "cheap" embossing since you can just use helmet or boot cores for chest/leg armor.

#### Expected Behavior:
I expect embossing using an armor core should require the same core type as the armor piece being embossed. Chest core for chest armor, helmet core for a helmet, etc.

#### Steps to Reproduce:
1. Make some armor.
2. Emboss using an armor core that isn't the same armor core type as the armor itself.
3. Receive (potentially) cheaper embossed item.

**Comment by TheIllusiveC4** [comment]
Excuse me if I'm misunderstanding the issue, but this seems like intended behavior to me. Or at least, it stays inline with Tinkers' Construct where you also don't need the corresponding tool part to emboss a trait.

**Comment by ghost** [comment]
You're right! This behavior is 100% normal apparently and I can emboss a scythe or dagger head onto a hammer.

Apparently I was so convinced this didn't make sense I didn't think to test the equivalent behavior in  TiCon, sorry about that.
