### ISSUE TITLE
Error Tconstruct vs conarm

### ISSUE THREAD

**Issue by pjindras** [TheIllusiveC4/ConstructsArmory#215]
<!--
I have this error in my console
* Construct's Armory: conarm-1.12.2-1.2.5.4
* Tinkers' Construct: TConstruct-1.12.2-2.13.0.183
* Mantle: Mantle-1.12-1.3.3.55
* Forge: 14.23.5.2852
https://pastebin.com/gWehxMu0

**Comment by TheIllusiveC4** [comment]
There's zero information provided, so I'm not really sure what this is even about. Please fill out one of the issue templates when you submit a new issue.
