### ISSUE TITLE
All armor is invisible, errors are thrown constantly, and there's a memory leak

### ISSUE THREAD

**Issue by Brycey92** [TheIllusiveC4/ConstructsArmory#216]
#### Versions (Be specific, do not write "latest"):
* Minecraft: 1.12.2
* Construct's Armory: 1.2.5.4
* Tinkers' Construct: 2.13.0.183
* Immersive Engineering: 0.12-92
* Mantle: 1.3.3.55
* Forge: 14.23.5.2838
* MODPACK: Galaxy-Craft Lite 1.0.7-1
#### Observed Behavior:
The armor is invisible, occasionally to you, and usually to other players. Additionally, the console is spammed with errors (see bottom of issue) and memory climbs well beyond the original allocated limit, presumably due to these errors.

I'm thus far unable to reproduce with only the mods listed above. However, I'm only able to test in singleplayer currently, so the issue might still happen on a server with the short mod list above.
#### Expected Behavior:
Armor should render properly, and the errors should either be caught or fixed so they're not thrown in the first place.
#### Steps to Reproduce:
1. Join a multiplayer server
2. Create a full armor set with Manyullyn cores, Ardite trim, and Steel armor plating. This is the only combination tested so far, though it may happen with others.
3. Wear it

One captured error as an example:
https://gist.github.com/Brycey92/1bdc612912a19e3c882cf823ac3421e6
The lines of conarm that error referenced:
https://github.com/TheIllusiveC4/ConstructsArmory/blob/master/src/main/java/c4/conarm/lib/client/DynamicTextureHelper.java#L46-L58
Entire log (something like 600MB, yikes):
[2020-04-11-2.log.gz](https://github.com/TheIllusiveC4/ConstructsArmory/files/4467119/2020-04-11-2.log.gz)

**Comment by Brycey92** [comment]
I fixed this by removing TexFix from my pack, for anyone interested.

**Comment by reddvilzz** [comment]
Hi, sorry for hijacking the issue. But how's the progress on this issue?

Will there a possible fix from Construct's Armory?

**Comment by Brycey92** [comment]
@reddvilzz No worries! As far as I know, there's been no fix made to Construct's Armory, though the dev(s) would be able to tell you for sure.
