### ISSUE TITLE
Texture glitch

### ISSUE THREAD

**Issue by zacharycollinsXIII** [TheIllusiveC4/ConstructsArmory#217]
I'm not to sure what i the cause of this I have not messed with the config or anything, and im not to sure how to fix this issue. basicly the armor texture is just really messed up for some reason and im not to sure why. and i have some mods in here with armor like thermal foundation and ice and fire along with the flans mod and thats about it with armor mods and im using the lastest version being right now (coarm-1.12.2-1.2.5.4) 
![2020-04-14_21 48 38](https://user-images.githubusercontent.com/63697122/79300571-fdb8d180-7e9b-11ea-9f6c-761c31bdc57e.png)

**Comment by TheIllusiveC4** [comment]
Can you provide a full mod list?

**Comment by zacharycollinsXIII** [comment]
i have apple skin
battle towers
baubles 
better nether
biblio craft
biomes of plenty
bountiful baubles
build craftz
cconarm 
coroutil
doomlike dungeons
dynamic surroundings
dynamic tress
extra tic
fany block particles
hwyla
ice and fire
ichunutil
instahouses
inven tweaks
iron chest
ivtoolkit
jei
llibrary
manyle 
minecolonies
mowziesmobs
nei
optifine
ore lib 
ores above diamonds
pam's harvest craft
place able items
place bo
portal gun 
projectE 
quality tools
quark
 reccurent complex 
rouge like dungoens
ruins mod
serene seasons 
silent lib
so many enchants
spartan weponry
tinkers con
toast+control
trinkers and baublrs
weather 2
worley caves

**Comment by zacharycollinsXIII** [comment]
oh nvm it seemed to fix it's self when i got rid of 
flan's 
applied energistics 2
and thermal expanssion
