### ISSUE TITLE
Armor models completely break down due to mod conflict.

### ISSUE THREAD

**Issue by BlueYoshi68** [TheIllusiveC4/ConstructsArmory#218]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.4
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Steps to Reproduce:
1. Install Conarm with this mod https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod.
2. Try wearing any armor.
3. Results.

**Comment by TheIllusiveC4** [comment]
Unfortunately this isn't something I can fix on my end. If I recall correctly, Vic's Modern Warfare does something to the player models which causes this issue.
