### ISSUE TITLE
Attacking with Telekinesis Does not Work in Survival

### ISSUE THREAD

**Issue by mobslayer202** [TheIllusiveC4/ConstructsArmory#219]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2 - 1.2.3
* Tinkers' Construct: 1.12.2 - 2.12.0.135
* Mantle: 1.12 - 1.3.3.49
* Forge: 14.23.5.2816
#### Steps to Reproduce:
1. Put a gauntlet of telekinesis on a con arm armor 
2. Get in Creative mode
3. Attack mob
4. Get in Survival mode
5. Attack mob
6. Compare 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
I can't fix this because this is vanilla behavior. There are checks in place so that players in Survival cannot hit entities from further than 3 blocks away and the Forge patch that enabled custom reach attributes didn't edit those checks to account for the feature.

**Comment by mobslayer202** [comment]
but how come hacked clients allow you to hit further away
