### ISSUE TITLE
Random Crash (May be a conflict but Idk.)

### ISSUE THREAD

**Issue by MagmaSlime123** [TheIllusiveC4/ConstructsArmory#224]
#### Versions (Be specific, do not write "latest"):
Forge 14.23.5.2854
conarm-1.12.2-1.2.5.4
MC 1.12.2

#### Observed Behavior:
Game crashes. I'm given a report and an error that's saying that this mod somehow caused this.
![image](https://user-images.githubusercontent.com/51277766/81365118-2b102e00-909c-11ea-8b22-4f95cd3587af.png)

#### Expected Behavior:
Game starting without crashing.

#### Steps to Reproduce:
Just use the mod. 

There may be a conflict Idk about, but crash reports just make my eyes bleed so I'm not even gonna try reading them.

#### Crash Log:
[crash-2020-05-07_19.47.35-client.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/4596755/crash-2020-05-07_19.47.35-client.txt)
If you won't use the file I gave then here's a link. Your welcome.
https://pastebin.com/UDv0AQ9S

**Comment by TheIllusiveC4** [comment]
That's from Armory Expansion, an add-on mod for Construct's Armory that was not made by me. You should post this on their issue tracker, wherever that may be.

**Comment by MagmaSlime123** [comment]
Oh... I had no clue. Sorry.

Like I said, crash reports just make my eyes bleed so I'm not even gonna try reading them.
