### ISSUE TITLE
Screen goes blank when entering F5. Couldn't Render Entity errors

### ISSUE THREAD

**Issue by Column01** [TheIllusiveC4/ConstructsArmory#226]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: `conarm-1.12.2-1.2.5.4`
* Tinkers' Construct: `TConstruct-1.12.2-2.13.0.183`
* Mantle: `Mantle-1.12-1.3.3.55`
* Forge: `1.12.2-14.23.5.2847`
#### Observed Behavior: 
When entering F5 with armor pieces that fail to render for some reason, the entire screen goes white.
#### Expected Behavior: 
It would render my armor and be fine
#### Steps to Reproduce:
1. Equip armor repeatedly until it eventually decides to not render properly
2. Enter F5 mode to look at yourself
3. Get a white screen

It doesn't crash but here is the log since it is relevant: [github gist](https://gist.github.com/c56d5505c1e78b717a6a53b98345d490)
It appears there are tons of texture loading errors starting [here](https://gist.github.com/Column01/c56d5505c1e78b717a6a53b98345d490#file-2020-05-21-1-log-L3751) in the log. Please let me know if you need any more info or if I can fix this due to a **PEBKAC** error or something of the sort. I should also add that FoamFix is installed as this is a Modpack that includes it (MC Eternal `1.3.5`) and the version is `foamfix-0.10.10-1.12.2`

**Comment by TheIllusiveC4** [comment]
I tried to fix the error happening on my end, but it looks like there are some texture issues happening outside of Construct's Armory itself that I can't really control so I can't guarantee that will address your problem entirely. If the problem persists, unless you can reproduce this issue with only Construct's Armory and its dependencies, it's likely out of my hands. At that point, I could only suggest tinkering with removing some mods that do texture stuff like FoamFix and see if that resolves anything.

**Comment by Column01** [comment]
Unfortunately due to this Modpack's size I cannot really remove FoamFix as it causes severe memory leaks without it loaded. Were you able to reproduce it at all using the core mods with foamfix installed?

**Comment by Column01** [comment]
It also appears that those files are still missing when loading without foam fix (I do not have other mods that affect textures like FoamFix or Optifine would) so I believe it's still an issue with the mod.

**Comment by TheIllusiveC4** [comment]
> Were you able to reproduce it at all using the core mods with foamfix installed?

Nope, with just FoamFix and Construct's Armory installed everything works fine for me. No errors when using F5.

> It also appears that those files are still missing when loading without foam fix (I do not have other mods that affect textures like FoamFix or Optifine would) so I believe it's still an issue with the mod.

Those files that you pointed to are not added by Construct's Armory, it's from somewhere else with integration for the mod. I can't really do anything about that.
