### ISSUE TITLE
Crash on Startup...Incompatibility w/ CraftTweaker?

### ISSUE THREAD

**Issue by TheVisionaryOne** [TheIllusiveC4/ConstructsArmory#227]
I apologize for the ambiguity of this issue, but I really can't get to the bottom of why it's happening, and I'd really like to use Construct's Armory in my pack. All I know is it has _something_ to do with Construct's Armory not playing nicely with CraftTweaker. I have CraftTweaker installed in my pack, haven't messed with it very much...and I haven't even tweaked anything related to Tinker's Construct. I added Construct's Armory to my pack as a test, and it crashes while loading. The crash log lists multiple suspected mods, but to my knowledge, they all just point to CraftTweaker, and aren't actually different mods.

**VERSIONS:**
* Construct's Armory: 1.12.2-1.2.5.9
* Tinkers' Construct: 1.12.2-2.13.0.183
* Mantle: 1.12-1.3.3.55
* Forge: 14.23.5.2847
#### Observed Behavior:
My pack crashes when loading. Only happens when Construct's Armory is present.
#### Expected Behavior:
Pack should load without crashing at the very least. It's been perfectly stable without Construct's Armory.
#### Steps to Reproduce:
1. Install my pack (it's still in the testing phase right now, but I can send a mod list, actual files, or whatever you need if you have the time to look into this issue)
2. Install Construct's Armory
3. Launch the game

Here's the [crash log](https://hastebin.com/meromopazu.rb).

**Comment by TheIllusiveC4** [comment]
Update CraftTweaker to at least 4.1.20.564.
