### ISSUE TITLE
Text Cut Off in Manual book

### ISSUE THREAD

**Issue by Nanorithm** [TheIllusiveC4/ConstructsArmory#231]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.4
* Tinkers' Construct: 2.12.0.157
* Mantle: 1.3.3.55
* Forge: 14.23.5.2846
#### Steps to Reproduce: 
1a. Open Manual
1b. (I am using Sphax texture pack, not sure if that matters)

Crash Log: No crashing, just a UX issue

This mod and Tinkers construct are literally the only mods I have issues with when it comes to books. Not sure what the issue is but I hope it can be fixed if all other books are working fine.

**Comment by TheIllusiveC4** [comment]
This mod leverages the same book as Tinkers' Construct (which I believe is actually from Mantle) so there's nothing I can do about it on my end.
