### ISSUE TITLE
Mod does not respect Tinker's Tool Leveling settings.

### ISSUE THREAD

**Issue by ptrxyz** [TheIllusiveC4/ConstructsArmory#233]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.5.9 
* Tinkers' Construct: 1.12.2-2.13.0.183
* Tinker's Tool Leveling: 1.12.2-1.1.0
* Mantle: 1.12-1.3.3.55
* Forge: 14.23.5.2852
#### Observed Behavior:
Starting "free modifier" amount of newly built armor is always 3, even when I change the initial modifiers using Tinker's Tool Leveling.

#### Expected Behavior:
The amount initial modifiers should be as much as I set them in the Tinker's Tool Leveling mod config.

#### Steps to Reproduce:
1. Install Tinker's Tool Leveling
2. Edit ```config\TinkerToolLeveling.cfg``` and set ```newToolMinModifiers=10```
3. Create a new Armor, i.e. all pieces from Cobblestone.
4. Check the new modifiers, they are 3.

**Comment by TheIllusiveC4** [comment]
This is because Construct's Armory has its own configuration for leveling. Check the Construct's Armory config for leveling options.

**Comment by ptrxyz** [comment]
Oh my dear, I was so blind.
Sorry for the report.

Keep up the good work.
