### ISSUE TITLE
diamond-plate bug

### ISSUE THREAD

**Issue by ColonelGerdauf** [TheIllusiveC4/ConstructsArmory#234]
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Observed Behavior:
When you replace a plate material of an armor that has diamond modifier, it seems not to display the correct toughness value.
#### Expected Behavior:
The action should replace the toughness value to that of the new plate material, plus two from the diamond modifier.
#### Steps to Reproduce:
1. Create an arbitrary armor set with obsidian plates (toughness 3.5)
2. Add a diamond modifier to the armor item
3. Replace the armor set with sponge plates. Ideally, the toughness should be 7, but is instead 5 or sometimes even lower. Other materials exhibit more bizarre anomalies in toughness values.

**Comment by TheIllusiveC4** [comment]
I am unable to reproduce this. Going through your steps, my armor ends up with 7 toughness as expected. Here's a gif of me demonstrating my testing:

![conarmverification](https://user-images.githubusercontent.com/29991504/85195710-a531f600-b289-11ea-9f5e-2f32f07abf1d.gif)

Can you reproduce your issue with only Construct's Armory and its dependencies installed?

**Comment by ColonelGerdauf** [comment]
Hmm... I could not currently reproduce this issue in a SP test world, but it has happened in a server, and I could have sworn that I had reproduced this error in a test world at some point. Perhaps the miscalculation came as a result of a conflict of mod settings.

In that case, it is unlikely to be an issue on your end, so I am going to close this.
