### ISSUE TITLE
Crash idw noobie

### ISSUE THREAD

**Issue by jimmy06200** [TheIllusiveC4/ConstructsArmory#237]
* Construct's Armory: 1.2.5..9
* Tinkers' Construct:2.13.0.183
* Mantle:1.3.3.55
* Forge:14.23.5.2847

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CraftTweaker2 (crafttweaker)
Caused by: java.lang.NoClassDefFoundError: crafttweaker/api/event/LivingKnockBackEvent

https://hastebin.com/fifevasoyo.rb

Thx to help me out with this one.
It appeared one day to an other without knowing what to do ...

**Comment by TheIllusiveC4** [comment]
Update CraftTweaker to its latest version.
