### ISSUE TITLE
Incompatibility with Avatar mod: Out of the Iceberg

### ISSUE THREAD

**Issue by GheriAl** [TheIllusiveC4/ConstructsArmory#239]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2854
#### Steps to Reproduce:
1. Have Avatar mod: Out of the Iceberg
2. Interact with armor station

Crash Log: https://hastebin.com/wodizefuge.rb

**Comment by TheIllusiveC4** [comment]
You should report this to the Avatar mod developers as the crash is occurring on their end. In the meantime, try setting the Compact GUI option to true in the Construct's Armory configs in order to avoid rendering the armor preview as a workaround.
