### ISSUE TITLE
Suggestion: Slime boots like bounce modifier

### ISSUE THREAD

**Issue by Pabilo8** [TheIllusiveC4/ConstructsArmory#24]
It would be nice to have a modifier on boots that allows bouncing just like the tinker's slime boots.

**Comment by TheIllusiveC4** [comment]
This is something I'm looking to include as soon as I can get to it.

**Comment by TheIllusiveC4** [comment]
Once Curse approves the newest update, the Slime and Blue Slime materials now have a Bouncy trait that can act like Tinkers' Slime Boots when used on the boots.
