### ISSUE TITLE
Recipes from CraftTweaker to Add Recipes

### ISSUE THREAD

**Issue by VinterNacht** [TheIllusiveC4/ConstructsArmory#240]
I have had no luck finding the instructions for this, but I swore I found them once. They're not on this wiki... Halp?

**Comment by TheIllusiveC4** [comment]
What do you mean by recipes from CraftTweaker? I'm not sure what you're asking.

**Comment by VinterNacht** [comment]
> What do you mean by recipes from CraftTweaker? I'm not sure what you're asking.

I was a doofus, and I figured it out. I was trying to go about things the wrong way.  I wanted to add construct armory recipes to *tinker's forging*.  That requires using crafttweaker on Tinker's Forging, not construct armory.  My bad!
