### ISSUE TITLE
Invisible Armors and Log Spams

### ISSUE THREAD

**Issue by reddvilzz** [TheIllusiveC4/ConstructsArmory#243]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory:  1.2.5.4
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Observed Behavior: 
Invisible Armors and a constant log spam, sometimes the armors will just show up, usually after a restart / entering the world. There's a temporary fix for the log spam by using cosmetics armor to hide the main armors from Construct Armory's.

#### Expected Behavior:
Armor should render properly, and the errors should either be caught or fixed so they're not thrown in the first place.

#### Steps to Reproduce:
1. Join and create armors and wear it.

...

Crash Log: Please use a paste site like [Log](https://gist.github.com/reddvilzz/5a8cdb2af30bd5e55497b1a8e4566762).

**Comment by reddvilzz** [comment]
#216

**Comment by TheIllusiveC4** [comment]
Are you able to replicate this behavior using only Construct's Armory, its dependencies, and no other mods?

**Comment by reddvilzz** [comment]
Sorry, was trying something and it just created another issue post.

Removing TexFix fixed it just like the issue posted on April, It's the same problem.

Testing your suggestion now.

**Comment by reddvilzz** [comment]
> 
> 
> Are you able to replicate this behavior using only Construct's Armory, its dependencies, and no other mods?

Here is the log spam while testing only ConArm and it's dependencies + TexFix.
[Log](https://gist.github.com/reddvilzz/c341421344bdad29eb28014a9619e5c1)

Without TexFix the armor shows up and no log spam.

Quoting the Author of TexFix from the comments section
>  Yep because tinkers construct loads the texture stuff after texfix has removed them and it waits 1 tick to unload them again.
 That means the mod has to either implement a proper fix or implement a cache during reload to improve this.

**Comment by Jennifercutixx** [comment]
if u have any other mod that is installed it can mess with the textures. quite a lot of mods conflict with tinkers armory bc this mod adds a new texture to the armor so when any animation mod or anything that changes ur player can mess with the mod. this issue happens alot. i have done alot of digging on this but how i solved it was installing mods one at a time and if the armor goes invisable on ur player uninstall the mod that causes it or just try not to notice it bc this could be a long time for this to be fixed since its not the mod its just compatiabilty .

**Comment by Jennifercutixx** [comment]
here's my page on this issue. on my issue page i have listed some mods that i found that conflict #207 
3 mods on my issue page i found that conflict with it. mind when i tested them it was only with tinkers armory plus mods needed for the mod to work. and one other mod with new configs.
the 3 mods are mo bends, inventory tweaks, the between lands.
if you have issues with other mods you have try posting on #207 for mod conflicts if u can to help out in finding mods that conflict.

**Comment by reddvilzz** [comment]
More detailed information on #207
