### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by George0079** [TheIllusiveC4/ConstructsArmory#250]
Whenever I try to view any form of completed armor in my inventory, no matter the material (even the default ones) my game crashes to desktop.
The game runs fine simply wearing the armor, but looking at armor icons for some reason crashes the game.

I do remember updating Construct's Armory recently as well as downloading additional mods for a pack I'm designing, but the problem is that all the mods I've added don't affect Construct's Armory in the slightest.

I suspect the culprit of any cross-mod shenanigans might be Thaumic Augmentations, but I can't be sure as nothing on that end has a similar bug. I'll be conducting my own experiments with Conarm and Thaum Aug isolated, but I have my doubts.

I've uploaded the crash report onto this post in case it yields more inciteful information.

The Minecraft launcher will display this message upon crash:
"The game crashed whilst rendering screen
Error: java.lang.ClassCastException: slimeknights.tconstruct.library.client.model.BakedSimpleItem cannot be cast to slimeknights.tconstruct.library.client.model.BakedToolModel
Exit Code: -1"

[crash-2020-12-04_06.03.25-client.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/5642585/crash-2020-12-04_06.03.25-client.txt)

**Comment by George0079** [comment]
Update: I've tested Conarm and Thaum Aug alone and the bug persists. Upon uninstaling Thaum Aug, the bug goes away.
I don't know why this happens with Thaum Aug, but we at least know it's something about those two.

Here's the crash report for the isolated incident:

[crash-2020-12-04_06.12.04-client.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/5642625/crash-2020-12-04_06.12.04-client.txt)

**Comment by TheCodex6824** [comment]
This was an issue on my end, I have a mechanic in my mod that hooks armor models and it seems like Tinker's Construct BakedToolModel instances return a BakedSimpleModel after calling handleItemState once. It copies the overrides to the simple model though, which always try to cast to BakedToolModel, which means trying to call handleItemState on the simple model crashes the game. It's not an issue with Construct's Armory, sorry for not catching this one before release.
