### ISSUE TITLE
collision with crafttweakers 

### ISSUE THREAD

**Issue by noseys** [TheIllusiveC4/ConstructsArmory#255]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2854
#### Steps to Reproduce:
1.makes the game stop when its loading all the mods showing a menssage only when the Construct's Armory its added
2. idk
3. just launch the game with crafttweakers 2 and Construct's Armory
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://paste.sh/y_BT0NJA#yNBateJo4Y4PuxTfpAWqlaFx

**Comment by TheIllusiveC4** [comment]
Update to the latest CraftTweaker version for 1.12.2. This issue is caused by using an outdated version.
