### ISSUE TITLE
Error adding traits to custom material

### ISSUE THREAD

**Issue by brisingraerowing** [TheIllusiveC4/ConstructsArmory#256]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.5.9
* Tinkers' Construct: 1.12.2-2.13.0.183
* Mantle: 1.12-1.3.3.55
* Forge: 14.23.5.2855
#### Observed Behavior:
The following errors pop up in the log and traits are not added

```
[INITIALIZATION][CLIENT][ERROR] Could not identify Trait <conarmtrait:magnetic>, it will not be added to material carbon
[INITIALIZATION][CLIENT][ERROR] Could not identify Trait <conarmtrait:magnetic_armor>, it will not be added to material carbon
[INITIALIZATION][CLIENT][ERROR] Could not identify Trait <conarmtrait:hellish_armor>, it will not be added to material carbon
[INITIALIZATION][CLIENT][ERROR] Could not identify Trait <conarmtrait:hellish_armor>, it will not be added to material carbon
```
(I did notice that hellish isn't available as an armor trait after getting this error, but magnetic is. And setting the default trait to hellish worked).
#### Expected Behavior:

Traits are added without errors.

Script: https://gist.github.com/BrisingrAerowing/6ed1957892397a2fd27c170aab1f0329

**Comment by TheIllusiveC4** [comment]
Where do the traits come from originally?

**Comment by brisingraerowing** [comment]
Magnetic and Hellish are built into Tinkers.

**Comment by TheIllusiveC4** [comment]
Because `magnetic` is a leveled trait, `magnetic_armor` needs the level info included. So the actual identifier would be `magnetic1_armor` for the level 1 magnetic trait. I know it's weird, but it's just a result of how the Construct's Armory and Tinkers' Construct's systems interacted.
