### ISSUE TITLE
1.12.2 Mo' Bends "support"

### ISSUE THREAD

**Issue by cloby0** [TheIllusiveC4/ConstructsArmory#257]
I have Construct's Armory and Mo' Bends on and whenever I equip a ConArm armor all the arm armor is on my left arm and my boots are behind my feet. The helmet is fine but every thing else is screwed. I don't know if this qualifies as custom animations because I don't make mods. I didn't know to report this as a Mo' Bends bug or a ConArm bug so I'm going to post this on both of them.

**Comment by TheIllusiveC4** [comment]
This is a Mo' Bends bug, as it has issues with several other modded armor models as well. There's not much that I can do on my end to address this.
