### ISSUE TITLE
Latest version causes loading crashes with CraftTweaker

### ISSUE THREAD

**Issue by beans-squared** [TheIllusiveC4/ConstructsArmory#258]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.10
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* CraftTweaker: 4.1.20.586
* Forge: 14.23.5.2855
#### Observed Behavior:
Attempting to start the game with the latest version of Construct's Armory, Tinker's Construct, Mantle and the latest stable version of CraftTweaker will result in a crash during Phase 2 initialization (see crash report).

This issue persists when upgrading CraftTweaker to the latest beta version (4.1.20.602).

Downgrading Construct's Armory to the previous version (1.2.5.9) fixes the issue.
#### Expected Behavior:
The game to start up as normal.
#### Steps to Reproduce:
1. Add Construct's Armory, Tinker's Construct, Mantle, and CraftTweaker (versions specified) to a new Forge 14.23.5.2855 instance.
2. Launch the game
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://gist.github.com/beans-squared/19c42c3da3bf81d16837bc701561097b

**Comment by TheIllusiveC4** [comment]
> This issue persists when upgrading CraftTweaker to the latest beta version (4.1.20.602).

That is not the latest beta version. The latest beta version is 4.1.20.614. Please upgrade to that, or downgrade Construct's Armory.
