### ISSUE TITLE
Crash with CraftTweaker

### ISSUE THREAD

**Issue by AechtRob** [TheIllusiveC4/ConstructsArmory#259]
I have a moderately large modpack and the latest update of ConArm 1.2.5.10 (from 1.2.5.9) causes the game to crash clientside on loading. Here is a crash report:

[crash-2021-01-22_19.49.10-client.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/5858253/crash-2021-01-22_19.49.10-client.txt)

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/258

Upgrade CraftTweaker or downgrade Construct's Armory.
