### ISSUE TITLE
Suggestion: Armor Padding

### ISSUE THREAD

**Issue by AppleNorris** [TheIllusiveC4/ConstructsArmory#26]
Like Coifs, Gambesons, Vests, Doublets, Greaves and Bracers. It will be more realistic because armor was rarely worn without padding to avoid bruises, scratches and to remain warm at nights or during winter. They can add some blast protection or arrow protection or fall protection e.t.c., just to make modifiers more diversified and unique.

Also I ask this because I really like your mod, but I am playing with 'Tough As Nails' installed and like for half of the minecraft year I am forced to wear Wool Armor for warmth instead of protection :( same with Jelled armor. It's going to be way easier if there will be a feature in this mod to complement TANs current lack of content by adding warmth and cooling factors to armor parts through padding or modifiers.

**Comment by TheIllusiveC4** [comment]
I like your idea, but I have to get all of this straight first. Are you basically asking for modifiers to add warmth and cooling to armor? And in addition, to give these hypothetical modifiers a slight amount of protection from blast/projectile/fall?

**Comment by kierajreed** [comment]
I think that's what it is. `Warming` and `Cooling` (hypothetical names) can be enabled if TaN is loaded.

**Comment by AppleNorris** [comment]
Basically, yes :) about additional protection - I thought that if TAN is not enabled then this feature with Warming and Cooling will have no use for players who like to use it only with TC, then I remembered that in Minecraft armor can be enchanted with those protections and thought - why not? Armor Padding was worn for the same reasons IRL, so it's not that far fetched for them to have same properties in Minecraft.

**Comment by TheIllusiveC4** [comment]
Okay, I got the gist of it. I'd be glad to add something like this, probably during the beta phase sometime.

**Comment by TheIllusiveC4** [comment]
I've been looking into how I could implement this, and I've tentatively decided against including this feature. I do so with some reluctance, so perhaps I could be persuaded to change my mind, but one of my core tenets for integration is to not completely obsolete another mod's features. 

Looking at how TaN implements the cooling/warming capabilities of the wool and jelled slime armor, they provide the minimal amount of bonus warming and cooling possible. If they had provided more, I could implement some slightly weaker modifiers as an alternative to their sets. As it stands, the rigidity of the temperature stat means that any implementation I provide would completely invalidate their armor sets, which I'm not entirely comfortable with doing.

**Comment by AppleNorris** [comment]
That's mostly because of how their warming and cooling works: you do something = you get warmer. But if player has no armor and no bonuses, their passive warming or cooling will be the same as in the athmosphere, and the time in which player can remain in cold or hot athmosphere decreases exponentially to which temperature he is in.
It works kinda like that: you have no armor and no bonuses - cold temperature will make player go into hypothermia very quickly, with time span of getting from hyperthermia to hypothermia in the coldest weather is around 3 minutes. And vice versa. With armor this time extends up to 10 minutes. Standing inside water decreases this time, dividing it by 2.
This is why their armor have such low stats and it's okay to have lower values.

Also, gelled armor is just plain useless. With Serene Seasons in the middle of summer player in gelled armor will go into hyperthermia in 3 minutes, regardless of whether he wears this armor or not. Probably miscalculation on their part, because they balanced this armor around nether and it's athmosphere.
You can say that in minecraft hell is colder than sunny weather in the middle of summer :P

**Comment by TheIllusiveC4** [comment]
That's all helpful to know, thanks for the explanation. I never played with TaN personally so it's hard for me to talk about without really knowing all of its mechanics in-depth.

However, my reservations still stand. Regardless of the usefulness, or lack thereof, of their armor sets, I'm not comfortable with obsoleting the utility of those armor sets when their utility is in regards to a mechanic that TaN itself also adds. It would feel like an intrusion into their internal gameplay balance, if that makes sense.
