### ISSUE TITLE
The Game crashes before it even loads me in

### ISSUE THREAD

**Issue by ijohn78** [TheIllusiveC4/ConstructsArmory#260]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.4
* Tinkers' Construct: 1.12.2-2.13.0.183 
* Mantle: 1.12-1.3.3.55  
* Forge: 14.23.5.2854
#### Observed Behavior: so i dont really know whats causing the crash to begin with so i dont really know how to reproduce it, all i know is that when i place the mod in the folder the game crashes, when i take it out it doesnt crash and runs in perfect condition. id like to try the mod out but i want to keep the others i have installed
if a full list of mods is needed i can provide the folder

#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/z79ufePF

**Comment by ijohn78** [comment]
oh
i just realized everything i typed got deleted
 there we go fixed

**Comment by TheIllusiveC4** [comment]
You're running a very old version of Construct's Armory. Please update to the latest version and it will solve your issue.
