### ISSUE TITLE
Ice and Fire support

### ISSUE THREAD

**Issue by nicholasrobertm** [TheIllusiveC4/ConstructsArmory#262]
**Please describe the new feature or change.**
As of Ice and Fire 1.8(1.12.2) it now supports tinkers tools OOTB. It'd be cool to have ice and fire included in materials automatically when installed to have matching armor sets to the tools

**Please describe why you want this feature.**
Dragonsteel is a cool material, seems simple enough to add

**Comment by TheIllusiveC4** [comment]
If it's Ice and Fire that has added support for Tinkers, then it'd also be up to them or another add-on to implement their materials for Construct's Armory. By default, Construct's Armory only supports materials added by Tinkers natively.
