### ISSUE TITLE
Mo' Bends x Constuct's Armory.

### ISSUE THREAD

**Issue by WaffleyAero** [TheIllusiveC4/ConstructsArmory#265]
I really like the mod but when i use the armor with mod "Mo' Bends" It glitches like it's strange not modeled random placed armor.
If You Can Please Fix That. :)

(Info:)
Version 1.12.2
Mods: Mo' Bends / Construct's Armory.
Feature: That Mo' Bends Can Work With Construct's Armory Because Armor Glitches.
![2021-02-24_10 11 33](https://user-images.githubusercontent.com/77974116/108967923-c3f25300-7688-11eb-8ff0-895db2bb1141.png)
![2021-02-24_10 11 37](https://user-images.githubusercontent.com/77974116/108967928-c5238000-7688-11eb-9a14-d58810793be3.png)
![2021-02-24_10 11 37_2](https://user-images.githubusercontent.com/77974116/108967932-c5238000-7688-11eb-84be-840e88b21a85.png)
![2021-02-24_10 11 42](https://user-images.githubusercontent.com/77974116/108967937-c6ed4380-7688-11eb-8598-9c7702d6f18f.png)
![2021-02-24_10 11 44](https://user-images.githubusercontent.com/77974116/108967938-c785da00-7688-11eb-940a-b3207b6dcaf0.png)
![2021-02-24_10 11 46](https://user-images.githubusercontent.com/77974116/108967941-c8b70700-7688-11eb-995a-a587ee592e7c.png)
![2021-02-24_10 15 07](https://user-images.githubusercontent.com/77974116/108968260-382cf680-7689-11eb-99c2-79c42e05820b.png)
(First Time Using Gihub Issues And Feature's Thingy :d )
(The last picture moves like glitching).

**Comment by TheIllusiveC4** [comment]
This is a known issue. However, since Mo' Bends also has this conflict with several other modded armors, this would be on the Mo' Bends developer to try and fix on their end.

**Comment by WaffleyAero** [comment]
Ok, Thank You!
