### ISSUE TITLE
Armor Bug with Viks MW/Viks Contagion

### ISSUE THREAD

**Issue by Kindomfighter** [TheIllusiveC4/ConstructsArmory#269]
I finally figured out what mod causes the issue, so the armor textures get messed up with the mod Viks MW or Viks Contagion (Either one I didn't check I removed both) and say the shoulder plates on the chest plate don't pop up, and you can see like little pieces of the armor sticking out of your player model.

**Comment by TheIllusiveC4** [comment]
This is caused by Vic's Modern Warfare and it is up to those developers to fix since this issue affects more armor than just Construct's Armory.
