### ISSUE TITLE
Port for 1.16.5

### ISSUE THREAD

**Issue by phaalonso** [TheIllusiveC4/ConstructsArmory#270]
Will be a port to minecraft 1.16.5?

**Comment by TheIllusiveC4** [comment]
Yes, there will. If anyone is interested in following development, please join my Discord server where I have a channel dedicated to discussion and design documents for the 1.16 port: https://discord.gg/JWgrdwt

**Comment by TheIllusiveC4** [comment]
I know it took a while, longer than I personally expected, but the first alpha for 1.16.5 has been released on CurseForge with a 1.18.2 port in the works as well. Thanks everyone for your patience and be sure to drop by the Discord if you have any suggestions or feedback for the new version.
