### ISSUE TITLE
game crashes whike creating armor using dark matter

### ISSUE THREAD

**Issue by dablade11577** [TheIllusiveC4/ConstructsArmory#272]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.2.5.10
* Tinkers' Construct:TConstruct-1.12.2-2.13.0.183
* Mantle:Mantle-1.12-1.3.3.55
* Forge: 14.23.5.2855
#### Steps to recreate: 
1. get a forge 
2. make the armor using any combination 
3. when you add dark matter the game just crashes
4. any other combination using not dark matter works
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://paste.ee/p/wQnD0

**Comment by dablade11577** [comment]
so update, the game is now crashing with any combination of armor

**Comment by TheIllusiveC4** [comment]
It seems like something in NotEnoughItems is crashing. Have you tried removing that mod and testing without?

**Comment by dablade11577** [comment]
just did that and the problem is still there

**Comment by TheIllusiveC4** [comment]
Okay, then what does the crash log say that time?

**Comment by TheIllusiveC4** [comment]
Also, try updating JEI to the latest for 1.12.2 which I believe is jei_1.12.2-4.16.1.301.

**Comment by dablade11577** [comment]
still happening heres another log with some mods updated https://paste.ee/p/g6stN

**Comment by TheIllusiveC4** [comment]
It seems like LLibrary is crashing now. I also don't see Construct's Armory in any of the stacktraces anywhere anymore, so I'm inclined to believe this is not a Construct's Armory issue.

**Comment by dablade11577** [comment]
so it wasnt llibrary which was a library for jurassicraft

**Comment by dablade11577** [comment]
im going to try to rund the game with and without constructs armory to see if it works

**Comment by dablade11577** [comment]
so it fixed it by removing constructs armory playing it than playing it with it installed again but whenever i try to use dark matter as an armor piece it start doing it again https://paste.ee/p/DYIJJ

**Comment by dablade11577** [comment]
so after playing with it i found out metallurgy was the problem, any armor made with anything from metallurgy crashes my game

**Comment by dablade11577** [comment]
im going to see if the most updated version works

**Comment by dablade11577** [comment]
so it did work

**Comment by dablade11577** [comment]
i was using a really old version but it was fixed
