### ISSUE TITLE
About 1.16.5

### ISSUE THREAD

**Issue by Cactusstudent** [TheIllusiveC4/ConstructsArmory#281]
Yesterday, I noticed that you update the constructsarmory to the 1.16.5. But i dont find the guide book. Maybe you should make one?
i think that will be great.
I noticed that you were writing a lot of desc about the armor. How can i see them in the game?
I think you can write it in the guide book. It will be great.

(By the way, i'm making the zh_cn.json for this mod)

Thanks a lot.

**Comment by Cactusstudent** [comment]
Oh, the last one, can you make a thing that we can hide the armor? it can help a lot of gamers. Thanks

**Comment by TheIllusiveC4** [comment]
The guide book has yet to be implemented, it will be in a future update. Some of the descriptions in the lang file are going to be used for that, but some of the others can be found as tooltips when you're building the armor in the Tinker Station/Anvil.

Making a feature to hide the armor may or may not come later, still to be decided.

**Comment by Cactusstudent** [comment]
Oh, i see. Thanks
