### ISSUE TITLE
[Question] The modifier named Salvaged in 1.16.5

### ISSUE THREAD

**Issue by Cactusstudent** [TheIllusiveC4/ConstructsArmory#282]
Well, i'm making the zh_cn for the 1.16.5, but i noticed that the modifier named `Salvaged`. I found many mods and wiki, but i dont found the correct material of this modifier. So can you tell me? Please!

**Comment by TheIllusiveC4** [comment]
It belongs on Ancient Hide, but it's not implemented yet.
