### ISSUE TITLE
Mod not able to load correctly/crash when added to Create Above and Beyond modpack

### ISSUE THREAD

**Issue by Enrico9431** [TheIllusiveC4/ConstructsArmory#284]
I don't know what exactly is wrong but I did test adding this mod onto a vanilla game and that resulting in working fine, so I have a feeling it would have something to do with another mod.

* Construct's Armory: 2.0.0-alpha.2+1.16.5
* Tinkers' Construct: 1.16.5-3.3.0.308
* Mantle: 1.16.5-1.6.147
* Forge: 36.2.20
#### Steps to Reproduce:
1. Download the Create Above and Beyond modpack
2. Add Construct's Armory
3. Launch the game

Crash Log: https://www.toptal.com/developers/hastebin/asahuzoriq.rb

[crash-2022-07-22_00.27.32-fml.txt](https://github.com/illusivesoulworks/constructsarmory/files/9164036/crash-2022-07-22_00.27.32-fml.txt)

**Comment by TheIllusiveC4** [comment]
You're using a very old version of Tinkers', update all your mods and retry.
