### ISSUE TITLE
1.16.5 construct's armory not working

### ISSUE THREAD

**Issue by Namekiangod77** [TheIllusiveC4/ConstructsArmory#285]
<!-
#### Notice
Please reproduce all issues without any other unnecessary mods before submitting.
-->
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: constructsarmory-forge-2.0.0-alpha.2+1.16.5
* Tinkers' Construct:1.16.5-3.3.1.316
* Mantle:1.16.5-1.6.147
* Forge:36.2.20
#### Steps to Reproduce: Open Minecraft with said mods

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

https://hastebin.com/juracacafe.properties

**Comment by TheIllusiveC4** [comment]
Update Tinkers' to the latest version, you're using an old version.
