### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by D3nnis3n** [TheIllusiveC4/ConstructsArmory#29]
See the following Crashlog:
https://gist.github.com/D3nnis3n/0b9a46b39a3ddaa0a684d501d4755930

**Comment by MxtressMyxx** [comment]
Same: NPE crash on server boot - removed mod for now. Crashlog:
https://gist.github.com/AnsuzThurisaz/227bfc0a7881cefc47b6ae897ab7201a

**Comment by TheIllusiveC4** [comment]
Sorry about that guys! I've pushed out a quick new update on CurseForge (awaiting approval) that should fix this.
