### ISSUE TITLE
[Request, Future] Leather Armor

### ISSUE THREAD

**Issue by ElvenChaos** [TheIllusiveC4/ConstructsArmory#3]
Leather armor should be a thing, and hopefully dye-able (if possible/reasonable). It actually makes sense as an armor material.

**Comment by TheIllusiveC4** [comment]
This is something I've considered. I'm focusing on getting the foundations down right now, but I'm definitely considering adding in leather armor and dyeing.

**Comment by ElvenChaos** [comment]
I'm aware it is far in the future, just wanted to put it out there while I was thinking about it. :P

**Comment by TheIllusiveC4** [comment]
I spent the better part of the last two days giving this an honest shot, and I've hit a dead-end as far as dyeing goes. The Tinkers' system just wasn't built with that kind of feature in mind. I have the leather material itself all set, but without being able to properly implement dyeing I can hardly find a reason to include it. I'll definitely revisit this idea if I can ever figure out a way to do this, but until then this feature will have to be set aside.
