### ISSUE TITLE
Manullyn Armor

### ISSUE THREAD

**Issue by Ceifeire** [TheIllusiveC4/ConstructsArmory#31]
When I wear pieces of this armor it is kicking me from my server after a few mins. Once I took it off all was well again. I was wearing it with steel legs and slime boots

**Comment by TheIllusiveC4** [comment]
Which version of Construct's Armory are you using? This should've been fixed in the latest update.

**Comment by Ceifeire** [comment]
0.0.11-a for MC 1.12.2

**Comment by TheIllusiveC4** [comment]
Okay, that's an old version. Please update to the newest version, 0.0.13-a. If the problem persists, please let me know.
