### ISSUE TITLE
Manyullyn Armor

### ISSUE THREAD

**Issue by Ceifeire** [TheIllusiveC4/ConstructsArmory#32]
Hey got another issue with manyullyn armor or maybe just helmets in general. When I have night vision activated is likes to briefly turn it off and back on while I am wearing my Manyullyn helmet. I am on he most up to date version.

**Comment by TheIllusiveC4** [comment]
What are you using to give you night vision? I'll need this information to see what kind of behavior I'm dealing with specifically. Theoretically, the intended behavior is that it should turn off and not back on.

**Comment by Ceifeire** [comment]
its a mod called vampirism. its permanent night vision.

**Comment by TheIllusiveC4** [comment]
Ah okay, so what's happening is that the Vampirism mod is probably constantly giving you night vision and Manyullyn armor takes it away every 5-20 seconds, which the Vampirism mod promptly re-applies. I'm probably going to have to just change the Prideful trait altogether, there's too many mechanics revolving around constant potion effects that prevent this from acting the way I want it to.

**Comment by Ceifeire** [comment]
I see the flavor you were going for there. I didnt properly read the prideful trait. I dont know if I would remove it. I should just make a different helmet.

**Comment by TheIllusiveC4** [comment]
I did end up removing this behavior from the Manyullyn material. Prideful now does something different that isn't related to potion effects, so you can use it with Night Vision.
