### ISSUE TITLE
[Enhancement] Make an API available

### ISSUE THREAD

**Issue by YaibaToKen** [TheIllusiveC4/ConstructsArmory#33]
Is there any API I could use to add materials? And if so, where is it located?

**Comment by TheIllusiveC4** [comment]
There's no formal API available yet, but you can look into the lib.materials package of the source code to see how the materials are handled and added. If you've ever worked with Tinkers' Construct, it's largely the same just with different types of material stats added.

**Comment by YaibaToKen** [comment]
As it pains me to say this.. is there a maven repo for the mod that I could use? Can't really figure out how to add this to my libraries 😢 though at least I figured out how to add the stats (not really that hard). Was looking to add compatibility for most metals xD so just need to register everything with your stats and parts.

**Comment by TheIllusiveC4** [comment]
Sorry, no maven repo or anything like that yet. You'll either have to figure out how to add this as a library as it is, or wait until the mod's a little more fleshed out with a proper API structure.

**Comment by YaibaToKen** [comment]
Managed to add your mod as library :)

**Comment by YaibaToKen** [comment]
Quick question, is there any place I can contact you, outside of the issues, mostly so I can discuss stats for the materials xD

**Comment by TheIllusiveC4** [comment]
If you have a CurseForge account, you could PM on there. Otherwise, you could e-mail me at itwasmec4@gmail.com.
