### ISSUE TITLE
Armor Tooltip doesn't say plates' material

### ISSUE THREAD

**Issue by YaibaToKen** [TheIllusiveC4/ConstructsArmory#34]
Just like the title, the tooltip will say what core and what trim and even the traits and stats, but the name of the plates will be missing.

**Comment by TheIllusiveC4** [comment]
If I'm understanding the issue correctly, then I cannot reproduce this.

![armorstuff](https://user-images.githubusercontent.com/29991504/39841844-34823a9c-53b2-11e8-86aa-ee7e4d3733d6.png)

Which version of Forge, Construct's Armory, and Tinkers' Construct do you have? And I assume you're encountering this in a setting with only these mods installed?

**Comment by YaibaToKen** [comment]
Tested this with just TConstruct-1.12.2-2.9.1.65, Mantle-1.12-1.3.2.24 and conarm-1.12.2-0.0.13-a loaded.
![image](https://user-images.githubusercontent.com/9133736/39842137-452aa53e-53dd-11e8-96b6-3cd781375993.png)

The armory tab also only shows a page for the chestplate, is this intended at this moment in time?
![image](https://user-images.githubusercontent.com/9133736/39842172-61b39c4c-53dd-11e8-8139-4e3fb99dc9db.png)

Edit: The screenshot of the missing info was taken inside a modpack I'm developing but it also happens with just the mods described.

**Comment by TheIllusiveC4** [comment]
Hm, very strange. I'll try updating my copy of Mantle as it's different from what you're working with, maybe something changed there. Otherwise, I'm having a hard time reproducing this.

As for the book, yeah, that's super WIP. I'll polish this up during the beta phase.

**Comment by YaibaToKen** [comment]
Could you tell me what version of mantle you're using? I'll see if it still happens on my side as well ;) might help

**Comment by TheIllusiveC4** [comment]
I was using 1.3.1.21, but I've updated to 1.3.2.25. Still cannot reproduce. I can't even tell what might be causing this problem, it's very weird that it's specifically only the plating. Which Forge version are you using?

**Comment by TheIllusiveC4** [comment]
Also, could you post a screenshot of this happening with only Construct's Armory and the required mods?

**Comment by YaibaToKen** [comment]
Forge-14.23.3.2679 though it stopped happening just now, so it might be a mod interfering. I'll test some more and let you know

**Comment by kierajreed** [comment]
Try test it with only this and this mod's dependencies, all on the newest stable version.

**Comment by TheIllusiveC4** [comment]
Are there any updates on this issue?

**Comment by YaibaToKen** [comment]
Sorry, I haven't had the time to find what mod is conflicting, so it might be better to close this for now.. If anyone wants to look into it, I can easily supply the modpack.

**Comment by Phantom5582** [comment]
I'm having this same problem. I'm using the Twitch client with the FTB Revelation mod pack. Added to that pack is this mod add on, Custom Lan Ports with Hammer Core(1.12.2-1.9.9.3), and More Player Models.

**Comment by TheIllusiveC4** [comment]
Using FTB Revelations 1.8.0, I'm able to see this behavior. Unfortunately, I still don't know what's causing it since it must be due to some interaction with another mod.

**Comment by kierajreed** [comment]
Maybe add a `mod conflict` label? These happen quite a lot.

**Comment by TheIllusiveC4** [comment]
I haven't figured out why yet, but the mod causing this is Quark.

**Comment by TheIllusiveC4** [comment]
Okay, so the reason for this is that Quark's Visual Stat Display feature in the Client Tweaks module iterates through the tooltip, finds the first tooltip with the word "Armor" in it, and then removes it. This is intended to remove the "Armor" stat display in vanilla, but it catches my "Armor Plates" tooltip first and removes that instead. You can disable that feature to test and see that the tooltip returns to normal.

Still thinking on the best way to fix this problem.

**Comment by TheIllusiveC4** [comment]
I've decided to open up an issue about this on Quark's github and let them handle it if they so choose. For those interested in following along:

https://github.com/Vazkii/Quark/issues/859
