### ISSUE TITLE
ERROR in latest version

### ISSUE THREAD

**Issue by YaibaToKen** [TheIllusiveC4/ConstructsArmory#35]
Here's an error log with the latest version ;) doesn't seem to crash the game though

https://gist.github.com/YaibaToKen/d6caf7f36eeae2d3d8ef9c53be6181b7

**Comment by TheIllusiveC4** [comment]
Oh, shoot, somehow overlooked this when working on the Embossment stuff. Not a huge error though. I'll fix it up in the next update.

**Comment by YaibaToKen** [comment]
No worries, just wanted to let you know *-goes read the forge documentation again in hopes of learning how to register items...-*
