### ISSUE TITLE
Calcic trait only works in creative

### ISSUE THREAD

**Issue by VallenFrostweaver** [TheIllusiveC4/ConstructsArmory#37]
#### Versions:
* Construct's Armory: 1.12.2-0.0.17-b
* Tinkers' Construct: 1.12.2-2.10.0.81
* Mantle: 1.3.2.24
* Forge: 14.23.3.2655

#### Observed Behavior:
Calcic armors give regen/repair only in creative mode
#### Expected Behavior:
Calcic armors give regen/repair in survival mode as well
#### Steps to Reproduce:
1. Wear Calcic traited armor
2. Drink milk in survival
3. Drink milk in creative

**Comment by TheIllusiveC4** [comment]
Whoops. Okay, looks like the event I was using does not work the way I thought it did. I'll work on a fix ASAP.
