### ISSUE TITLE
Armor Station/Forge GUI Problems

### ISSUE THREAD

**Issue by radzo73** [TheIllusiveC4/ConstructsArmory#38]
Versions:
Construct's Armory: 0.0.17-b
Tinkers' Construct: 2.9.1.65
Mantle: 1.3.2.24
Forge: 14.23.3.2655

Observed Behavior:
your second layer of skin (hat, jacket, pants, etc) do not appear in the Armor Forge/Armor Station GUI
Expected Behavior:
your second layer of skin (hat, jacket, pants, etc)would appear in the Armor Forge/Armor Station GUI
Steps to Reproduce:
1. Open your Armor Station or Armor Forge
![2018-05-21_07 48 45](https://user-images.githubusercontent.com/26673668/40306132-744b80ee-5ccb-11e8-8d69-bd9651f78bf3.png)
![2018-05-21_07 49 06](https://user-images.githubusercontent.com/26673668/40306133-7457f644-5ccb-11e8-9c19-965aa628d38f.png)

**Comment by TheIllusiveC4** [comment]
Hm, interesting. Not entirely sure how this is all happening, but I'll look into it.

**Comment by TheIllusiveC4** [comment]
Figured it out! Just had to copy some of the model data when the fake preview player is initialized.
