### ISSUE TITLE
Creative Modifier's don't work on Construct Armor

### ISSUE THREAD

**Issue by radzo73** [TheIllusiveC4/ConstructsArmory#39]
Construct's Armory: 0.0.17-b
Tinkers' Construct: 2.9.1.65
Mantle: 1.3.2.24
Forge: 14.23.3.2655

Observed Behavior:
They work on other Tinker's tools (such as Crossbows, Yo-yo's, and Katanas, but you can't get additional modifiers on Construct Armor using Creative Modifiers ("No modifier found for Creative Modifier")
Expected Behavior:
You can use Creative Modifiers on Construct Armor to gain additional modifiers.
Steps to Reproduce:
1.Try to put Creative Modifiers on Construct Armor
![2018-05-21_08 01 31](https://user-images.githubusercontent.com/26673668/40306883-5c2d9904-5cce-11e8-84ec-dc9961f1be5d.png)
![2018-05-21_08 01 51](https://user-images.githubusercontent.com/26673668/40306884-5c3af216-5cce-11e8-8f9d-6dc687149a91.png)
![2018-05-21_08 09 51](https://user-images.githubusercontent.com/26673668/40306885-5c4ff044-5cce-11e8-9558-20fb2f552bd5.png)
![2018-05-21_08 10 07](https://user-images.githubusercontent.com/26673668/40306886-5c61d3c2-5cce-11e8-9976-540deb63f539.png)

**Comment by TheIllusiveC4** [comment]
This is a known issue, already resolved in dev environment so you'll see a fix in the next update.
