### ISSUE TITLE
Modifiers not working

### ISSUE THREAD

**Issue by QAngelusQ** [TheIllusiveC4/ConstructsArmory#4]
Iron Chestplate
![2018-02-19_00 38 56](https://user-images.githubusercontent.com/35056074/36363734-51ebe79c-150d-11e8-8b30-e1665300766d.png)
Materials and You - Armory Addendum
![2018-02-19_00 33 18](https://user-images.githubusercontent.com/35056074/36363651-abed6140-150c-11e8-9104-b24b3d23dd18.png)

Not 100% sure if i'm doing it right but I assume its similar if not the same as Tinker's Construct (with the exception of using an armor forge rather than the tools forge)

I looked in the book but when I clicked modifiers I got forwarded to the Steel Page.

**Comment by ElvenChaos** [comment]
Modifiers are Not Yet Implemented. See the curse forge page.

**Comment by TheIllusiveC4** [comment]
ElvenChaos is correct, modifiers are not yet implemented. There's a bookmark for them in the index, but that's just a placeholder. As I update the mod with new modifiers (which will be very soon as a lot of the coding for them is done already, I just need to test them), there will be pages added to the book to illustrate that fact.
