### ISSUE TITLE
Preview mode doesn't always work when connected to other Tinker tables

### ISSUE THREAD

**Issue by VallenFrostweaver** [TheIllusiveC4/ConstructsArmory#41]
#### Versions:
* Construct's Armory: 1.12.2-0.0.17-b
* Tinkers' Construct: 1.12.2-2.10.0.81
* Mantle: 1.3.2.24
* Forge: 14.23.3.2655

#### Observed Behavior:
Placing down an Armor Stand or Forge next to other Tinker tables (allowing them to connect for the tabs to be useable) the player preview no longer works.
#### Expected Behavior:
See player preview when tables are connected.
#### Steps to Reproduce:
1. Place other Tinker tables (ie Crafting Station, Tool Station/Forge, etc)
2. Place Armor table of choice next to these.

**Comment by TheIllusiveC4** [comment]
Hm, no idea what's causing this at the moment. Preliminary checks show that the preview is initialized correctly, it's just not drawing it to the screen for some reason when the tables connect. I'll look into it some more.

**Comment by TheIllusiveC4** [comment]
Alright, figured it out. I had the fake player on the background layer so it was being drawn over by the panel itself. Still not sure why it only happens when the Tinker tables are connected, but the problem has been solved.
