### ISSUE TITLE
Traveller's Goggles zoom too much.

### ISSUE THREAD

**Issue by VallenFrostweaver** [TheIllusiveC4/ConstructsArmory#42]
#### Versions:
* Construct's Armory: 1.12.2-0.0.17-b
* Tinkers' Construct: 1.12.2-2.10.0.81
* Mantle: 1.3.2.24
* Forge: 14.23.3.2655
#### Observed Behavior:
Goggles zoom. Like, really really really zoom.
#### Expected Behavior:
A decent zoom but not so much that I'm seeing 1 pixel at 300 blocks out.
#### Steps to Reproduce:
1. Wear Traveller's Goggles modified helmet
2. Use zoom hotkey

NOTE: I have to say that this may just be intended behavior but I find it a bit much. The slightest movement also moves so quickly at that distance it's very disorienting. I think it's just a bit too zoomed in.

**Comment by TheIllusiveC4** [comment]
Sure, I can tone it down a bit.

**Comment by TheIllusiveC4** [comment]
Actually, can you include a picture of what you're seeing just so I can make sure we're on the same page? Seeing 1 pixel at 300 blocks out doesn't sound quite like what I'm experiencing, but that could just be my perception.

**Comment by VallenFrostweaver** [comment]
By 1 pixel I meant that with no zoom it's enlarging the one pixel that my crosshairs are centered on. I'm out and about at the moment. I'll get you an image comparison when I get back in.

**Comment by TheIllusiveC4** [comment]
Thanks, it'll just help give me a reference point to work from. In the meantime, I've already made some code adjustments that tones down the zoom and makes the zooming transition smoother so hopefully it just feels better all around.

**Comment by VallenFrostweaver** [comment]
Well I got back and got stuck with other stuff and completely forgot. Apologies for that. I went to check just now and saw your update and things look much better! That is a very pleasant zoom level to me. Thanks you very much for considering and even more for implementing it.
