### ISSUE TITLE
Mod Compat Issue: Armor Rendering is Broken with Mo' Bends 

### ISSUE THREAD

**Issue by SargeRyong** [TheIllusiveC4/ConstructsArmory#44]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 0.0.17-b
* Tinkers' Construct: 2.10.0.81
* Mantle: 1.3.2.24
* Forge: 14.13.3.2698
* Mo' Bends 0.24

#### Observed Behavior:
Constructs Armory equipment rendering is incorrect on player model.  

#### Expected Behavior:
Equipment renders as intended.

#### Steps to Reproduce:
1. Install both Construct's Armory and Mo' Bends, making sure that Mo' Bends is enabled for player models in it's config.
2. Enter a world and equip helm,  chestplate, legguard, or boots from Construct's Armor.
3. Observe that the rendering is incorrect (textures seem to render on the wrong sides or in incorrect orientations?  Unsure, it just looks like a mess)
4. Uninstall Mo' Bends or disable player model changes and retry, observing that the rendering is once again as expected.

Crash Log: N/A

**Comment by TheIllusiveC4** [comment]
This is a valid issue; however, my hands are tied on this one. Considering that mod is closed source and there are open issues affecting other mods' armor as well, I think Mo' Bends needs to handle this on their end. I don't do anything particularly special to render the armor models.
