### ISSUE TITLE
config boolean Toggle to remove preview window

### ISSUE THREAD

**Issue by Adarcer** [TheIllusiveC4/ConstructsArmory#47]
I would like to be able to Remove / Disable the preview window, I find it immersive breaking does not even show what i am wearing at the time. and since i use Mobends and cosmetic armor  it makes it look like my character is frozen mid jump. and the fact i use cosmetic armor how the armor looks is not impostatant as i can change the look at any time...

**Comment by TheIllusiveC4** [comment]
Part of the design of the preview is also to fill in the large amount of empty space to the left that will never be filled up by anything else. But I suppose it does no harm to add this if that's what you really want.

**Comment by Adarcer** [comment]
Yah ... but it also pushes my JEI causing the number of pages up from 45 pages to 68. i also think the icons for the armor pieces would look  better along the sides

**Comment by TheIllusiveC4** [comment]
The newest update has a config option for "Compact GUI", which is hopefully exactly what you want. It removes the armor preview panel entirely and lines the armor piece buttons along the side.
