### ISSUE TITLE
[Modifier Suggestions] Pistons, Silky Jewel, Enderpearl + Obsidian, Pumpkin, Dragon Head

### ISSUE THREAD

**Issue by Thunder-Nova** [TheIllusiveC4/ConstructsArmory#49]
Multiple suggestions, Ability might be renamed by the mod creator as see fit.

## Piston
When placed on boots: Fall Damage Reducer (I would have said slime boots, but has been suggested)

When placed on Chestplate: (Show on arms) adds Knockback to bare punches

## Silky Jewel
Silk Body: When attacked by mob, raises the chance to drop their statues, durability is cut in half.

## Enderpearl + Obsidian
Self-Mutilation: Helmet only modifier, when player dies they drop their own head.

## Pumpkin
Jack-o-helm: Helmet only slot: Prevents enderman to get aggro when looked at. Blurs Vision with pumpkin blur.

## Dragon Head
Drag-o-helm: Same as above but no blur.

**Comment by TheIllusiveC4** [comment]
I'll consider the Pumpkin modifier, but probably not the other ones.

**Comment by Thunder-Nova** [comment]
np, though was kinda mostly making a parallel with TiCon with some modifiers, with some extras using vanilla mechanics (Pumpkin), and perhaps a use for the dragon head (not many mods uses it).

**Comment by TheIllusiveC4** [comment]
I tried to make the pumpkin thing work, but the necessary checks for this are hardcoded into the Enderman AI routines and locked behind a package-private inner class. Preliminary ways I've tried to work around this haven't worked, so for the moment I'll let sleeping dogs lie.

**Comment by Thunder-Nova** [comment]
Ok no problem
