### ISSUE TITLE
Feature Request: Step Assist Modifier

### ISSUE THREAD

**Issue by dannydjdk** [TheIllusiveC4/ConstructsArmory#50]
Could you add a step assist modifier that allows you to walk up a block without jumping similar to the Botania Sashes? Alternatively, it would be great if this could be included with the shulkerweight modifier. Jump boost can be painful without step assist.

Also, a fall protection modifier would be very nice as well.

**Comment by TheIllusiveC4** [comment]
Step assist should be available in the form of the High Stride modifier in the latest update.

Fall protection is available through the Featherweight trait from Cobalt material and the Bouncy trait on boots from Slime material. I have one more form of fall protection coming in the next couple updates or so, but I will not be adding a straight "minus x% fall damage" modifier.

**Comment by dannydjdk** [comment]
Sounds great! Sorry, I'm not sure how I missed the High Stride modifier. I'm looking forward to the other form of fall protection. The featherweight is great, but of course, like everyone, I always want more! ;) Either way, I love this mod, and am really looking forward to playing it more! Thanks for your hard work!

**Comment by dannydjdk** [comment]
The High Stride modifier does not appear in the book for 0.0.19-b.

**Comment by TheIllusiveC4** [comment]
Whoops, forgot to list it in the index. I'll fix this in the next update.

In the meantime, everything about it should still work. Try modifying a pair of boots with two regular pistons.
