### ISSUE TITLE
Modifier suggestion: Elytra modifier

### ISSUE THREAD

**Issue by Trinsdar** [TheIllusiveC4/ConstructsArmory#53]
Perhaps you could add a modifier that allows you to attach an elytra to the chestplate.

**Comment by TheIllusiveC4** [comment]
Sorry, but the logic is hardcoded for the elytra flight checks and I don't want to do any coremodding in this mod. I'll look into it again if Forge accepts my pull request for the elytra flight attribute or if some other update happens.

**Comment by Pirateboy04** [comment]
Forge did update this, according to [this bug report](https://github.com/MinecraftForge/MinecraftForge/pull/4476)

**Comment by Avakining** [comment]
This was/is being worked on [here](https://github.com/MinecraftForge/MinecraftForge/pull/4476)

**Comment by TheIllusiveC4** [comment]
@Pirateboy04 
That one was closed for inactivity, mine is a more recent and currently updated one that is based off the same PR: https://github.com/MinecraftForge/MinecraftForge/pull/4958
