### ISSUE TITLE
[Suggestion] Mod Exclusives Modifiers - (Hopefully a side project)

### ISSUE THREAD

**Issue by Thunder-Nova** [TheIllusiveC4/ConstructsArmory#55]
Yea, another suggestion sorry, though just though of it, and mostly want an opinion with it as well.

## Story
When I was playing the All The Mods 3 modpack, I was playing around in making jetpacks and then when I saw the armored Jetpacks, with my current Armor on myself, I was thinking. Why not.

Then I remember when Tinker had modifiers that existed with a required mod, but doesn't force to have such mods. So hoping it would be possible to make it that way as well.

## Suggestion

Note: The Modifiers Act as **Accessory**, meaning the 1 accessory rule applies to them. To avoid making the armor overpowered, with a few exception depending on the mod original intention.

 - Jetpack (Tier)
**Mods**: Mekanism / Simply Jetpack
Uses a Jetpack to permanantly be added as an Accessory modifier for the chestplate.  With the RF 1/2 of the used Jetpack.

- RF Boost (Tier) (Not accessory):
**Mods**: Ender IO / Draconic Evolution / Immersive Engineering / Thermal Expansion
The armor will act as a portable battery, it won't affect durability, nor defence. But can charge items on the toolbar, and body. This modifier is upgradable, with a higher tier Capacitor. If the mod author can make it possible to make the level of the RF of the capacitor used.

- Solar:
**Mods**: Ender IO / Actually Additions / Mekanism Generators / Tech Reborn
Uses Solar Panel as an Accessory modifier for the helmet. Like the jetpack, it holds half the RF, but will make as much RF as the solar power.

- Goggles of Revealing
**Mod**: Thaumcraft
Pretty much self explanatory, but an Accessory modifier using the Goggles of Revealing for the helmet, won't have the vis discount.

- Apiarist
**Mod**: Forestry
Uses the Apiarist armor of Forestry as Accessory Modifier for their respective armor. Respectively gives the effect of an Apiarist.

- Probing
**Mod**: The One Probe
A non-accessory Modifier, that uses The One Probe. Pretty much self explanatory on it's effect. (only need 1)

If anyone wants to add to the suggestion feel free, but don't forget to add the Mods that it uses. Usually to avoid making the author search for them.

**Comment by TheIllusiveC4** [comment]
Sorry, but I won't be implementing mod exclusive modifiers. I'd rather suggest that the author of those mods implement modifiers themselves if they so choose, as they'd best understand how to integrate such a feature with their mod's internal balance. In addition, I want to keep from bloating this mod with a bunch of optional abilities and keep the feature set as close to base Tinkers' as possible.

**Comment by Thunder-Nova** [comment]
Understandable, though I was thinking a way perhaps a mod addon. Such as PlusTic as example. I might ask PlusTic to check your mod hopefully to add more materials for it.
