### ISSUE TITLE
Autoforge does not repair armor when on fire

### ISSUE THREAD

**Issue by LordHellscream** [TheIllusiveC4/ConstructsArmory#57]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 0.0.21-rc1
* Tinkers' Construct: 1.12.2-2.10.1.84
* Mantle: 1.3.2.24
* Forge: 14.23.4.2707

#### Observed Behavior:
Magma slime armor doesn't repair damage: it seems like the armor simply doesn't take damage from fire, but it doesn't actually "rapair" itself as described.
So it not useful at all, since first of all the  player need to hurt himself to jump into the fire, and even if the fire doesn't really damage the armor, it doesn't do anything positive. 
At the end of the day, you lose HP (to get yourself on fire) but gain nothing.
#### Expected Behavior:
The armor should have a net-positive gain on armor HP when player is on fire. (essentially trading HP for repair like parasitic modifier)
#### Steps to Reproduce:
1. magma slime armor, steel plate, netherrack trim (full suit of armor or at least 2 pieces)
2. do some damage to the armor
3. make a fire with netherrack and flint and steel, sit on the fire and monitor the HP of the armor.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
The actual behavior that I'm seeing is that it does repair damage, but only when you're standing directly in the fire. This is because damage while you're IN fire is subject to armor protection and calls the necessary armor damaged method, but damage while you're ON fire bypasses armor and skips the check. I'll fix this in the next update.

**Comment by LordHellscream** [comment]
it's not true, i was standing in fire the whole time. the behavior is exactly the same (armor HP doesn't change)

**Comment by TheIllusiveC4** [comment]
In the future, please refrain from saying "it's not true" in reference to observed behavior. Differences in observations do not necessarily imply any sort of falsehood from either party. This is what I see, following your reproduction steps exactly.

![issue57](https://user-images.githubusercontent.com/29991504/41196833-5a8fdcd4-6c18-11e8-913c-fff3a17b126f.gif)

**Comment by LordHellscream** [comment]
this is very strange, i am doing the exact same thing and the HP does not recover (or go down).
One thing that may be different is that i was wearing full set of armor (exactly same settings). Not sure if that make a difference or not.

**Comment by TheIllusiveC4** [comment]
It's possible. Either way, I changed the code for this behavior in the dev build already so try it out once I can push out a new update.

**Comment by LordHellscream** [comment]
Ok i did some additional testing, as I suspected, when wearing a full suit, the HP doesn't change anymore. but just wearing one piece of armor by itself it does get repair like you have shown in the gif.

**Comment by TheIllusiveC4** [comment]
Okay, I'll make sure to test this behavior before pushing out the next update.

**Comment by LordHellscream** [comment]
https://i.gyazo.com/22a508f0fd9ac24aa4b26914e820b603.gif?_ga=2.217728726.1985907652.1528590274-1344001767.1516173486
