### ISSUE TITLE
The resistance modifier doesn't appear to be working

### ISSUE THREAD

**Issue by combustionsquirrel** [TheIllusiveC4/ConstructsArmory#58]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2 - 0.0.21-rc1
* Tinkers' Construct: 1.12.2 - 2.10.1.84
* Mantle: 1.12 - 1.3.2.24
* Forge: 2705

#### Steps to Reproduce:
1. Made an armor set, one with the resistance maxed out and one without resistance
2. Put the armor on a dummy from MmmMmmMmmMmm (version 1.14)
3. Hit both of them with an enchanted diamond sword and got the same damage number (tested with multiple armor sets)
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
This is because armor abilities only work when the armor is worn by a player, so the test dummy will not reflect accurate damage values. As far as I can tell from internal testing, the Resistance modifier is working as expected.
