### ISSUE TITLE
Suggestion regarding Traveller's Gear

### ISSUE THREAD

**Issue by septemberWaves** [TheIllusiveC4/ConstructsArmory#6]
Since the mod currently lacks modifiers _and_ you want to find some way to integrate the old Traveller's Gear, I think it would make sense to add the Traveller's Gear as armour modifiers. Craft the Traveller's Gear parts to be added to the armour, and then add them to any set of armour with a free modifier as normal to gain the effects.

**Comment by TheIllusiveC4** [comment]
This is one of two possibilities I'm considering right now. The second possibility I'm considering is adding a separate, single "augment" slot to each armor piece that would allow you to switch them out as necessary. An example would be that the Helmet could have a Goggles slot as its augment, and possible augments would be the Traveller's Goggles, Night Vision Goggles, Thermal Goggles, etc. But this might be needlessly complex, so it's just food for thought for now.

**Comment by ElvenChaos** [comment]
The "augment" system may seem needlessly complex, but it is better than trying to add even more player equipment slots (as was done before). And the implementation could be simpler than it sounds: the "augments" are just modifiers that care about the piece of armor they are attached to, and are mutually exclusive on the same piece of armor. Whether or not it counts as a "free augment" is just a balancing or design decision that is easily changeable in this case.

And honestly, some complexity might be a good thing to lean into the flavor of "tinkering" with the armor. Might be up for debate. Might be fun to turn players into Inspector Gadget.

**Comment by TheIllusiveC4** [comment]
Implemented as of commit 660fe07d8bf607abf28521809f0387b7c83ccdcd
