### ISSUE TITLE
NoSuchMethodError crash with TiC 1.12.2-2.10.1.87

### ISSUE THREAD

**Issue by TheIllusiveC4** [TheIllusiveC4/ConstructsArmory#60]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-0.0.21-rc1
* Tinkers' Construct: 1.12.2-2.10.1.87
* Mantle: 1.12-1.3.2.24
* Forge: 1.12.2-14.23.4.2705

#### Observed Behavior:
Construct's Armory will throw a NoSuchMethodError exception during initialization when loaded with Tinkers' Construct 1.12.2-2.10.1.87.

#### Expected Behavior:
Both mods will load just fine.

#### Steps to Reproduce:
1. Start Minecraft with both Construct's Armory and Tinkers' Construct loaded with the above specified versions respectively.

Crash Log: https://paste.dimdev.org/nokigoyomu.mccrash

**Comment by WrongWeekend** [comment]
I'm getting the same crash. How were you able to solve it?

**Comment by MatrexsVigil** [comment]
Also getting this error as well.  Does anyone have way to fix this?

**Comment by TheIllusiveC4** [comment]
This is caused by Tinkers' changing the parameters of a certain method in the latest update. Unfortunately, the only way to solve this is to just not use either Construct's Armory or the latest Tinkers' Construct version until I can push out an update, which I plan to do tonight as soon as I can.

**Comment by KnightMiner** [comment]
Yeah, sorry about that. The method was not part of our API so it normally would be safe to change, but I forgot to consider that Construct's Armory might be using the function. I could add back in the old signature, but by this point it sounds like you have a release planned anyways to fix it.

**Comment by TheIllusiveC4** [comment]
It's perfectly alright, it's trivial to fix on my end and you shouldn't have to worry about changing/removing methods that aren't part of the API.

**Comment by winsrp** [comment]
same on our server, same log

**Comment by TheIllusiveC4** [comment]
Fixed in 04efc75c52cbc700aa213d634c7eacf740c731bf
