### ISSUE TITLE
Just Some Requests.

### ISSUE THREAD

**Issue by Niconoko** [TheIllusiveC4/ConstructsArmory#64]
As the topic said:
- Different looks of armors.
- Modifier to make armors invisible. (cosmetic)

That's it, thanks in adv. :3

**Comment by TheIllusiveC4** [comment]
I'd love to have different armor looks, but well, just this one armor set was a lot of work for me. So, even just one more set probably won't happen for a while. If any potential modellers/texturers are looking at this, feel free to contact me about developing more armor models.

As for your second suggestion, hmm, sure. I could do that.
