### ISSUE TITLE
Twilight forest materials

### ISSUE THREAD

**Issue by milibucket** [TheIllusiveC4/ConstructsArmory#65]
Since Tinker's construct have native interactions with twilight forest already, I want to suggest to add twilight forest materials for constructs armory, 
like the naga scale, steel leaf, fiery and knightly metal

**Comment by YaibaToKen** [comment]
To be fair, I believe it's Twilight Forest that implements it's own integration with Tinker's Construct, As such, and as it is already in progress, it befalls TF to integrate with Construct's Armory and not the other way around. Not to mention that the owner of CA has said before he does not wish to detract from the base materials available in TiC.

**Comment by kierajreed** [comment]
@milibucket if you want to add Twilight Forest integration, you can make a Construct's Armory add-on to do exactly that and maybe also add other materials like ExtraTic does for Tinker's.
