### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by winsrp** [TheIllusiveC4/ConstructsArmory#66]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.0.0
* Tinkers' Construct:2.10.1.87
* Mantle:1.3.2.24
* Forge:2655

#### Observed Behavior:

game crashes while loading

#### Expected Behavior:

game loads

#### Steps to Reproduce:
1. just open the minecraft client, while loading forge components error shows up.

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

https://pastebin.com/b3gFP6ep

**Comment by TheIllusiveC4** [comment]
You're on an older version of Forge. Please update Forge to at least version 1.12.2-14.23.3.2694, or preferably the current recommended version 1.12.2-14.23.4.2705.
