### ISSUE TITLE
Constructs' Armory / Tough As Nails Integration

### ISSUE THREAD

**Issue by wendall911** [TheIllusiveC4/ConstructsArmory#68]
I've integrated Constructs' Armory into my mod Tinkers' Survival. As a part of that integration, Tough As Nails heating and cooling materials were added. This is more of a way to notify you that this is done, as I think this may be the first integration.

https://minecraft.curseforge.com/projects/tinkersurvival
https://github.com/wendall911/TinkerSurvival/tree/master/src/main/java/tinkersurvival/integrations

Fantastic work on your mod! It has been a real pleasure to use, and an inspiration for adding features to our original idea of just Tinkers' Construct tools/weapons.

**Comment by TheIllusiveC4** [comment]
Thanks for letting me know, that looks pretty cool! I'll be sure to suggest your mod to people who are interested in having TaN support with Construct's Armory.
