### ISSUE TITLE
Content Tweaker integration similar to Tinkers

### ISSUE THREAD

**Issue by Dragnier** [TheIllusiveC4/ConstructsArmory#69]
Tinkers construct has integration with Content Tweaker to allow adding materials and traits. Perhaps you could look at how this is accomplished and implement something similar with your mod? (possibly with the help of the Content Tweaker mod author) This would allow anyone to make custom materials and traits for your mod to fit their needs.

For example, I just got finished making my own materials for Astral Sorcery Aquamarine, Star Metal, a form of Rock Crystal, and an alloy that requires all three of those plus a custom ingredient; all with traits. However, those do not carry over to your mod at the moment.

**Comment by TheIllusiveC4** [comment]
Okay, I'll look into it.

**Comment by TheIllusiveC4** [comment]
@Dragnier Do you think you can link me a copy of your scripts for your ContentTweaker custom materials? I'd like to do some testing and it'd really help to have a real example to work with.

**Comment by Dragnier** [comment]
There is more to it than that... They rely on other mods. I'll attach an export of the curse modpack profile so you can make sure you have everything. To be honest, this is just an early alpha of the pack I'm making, so I haven't gone back through the scripts to make sure they all have the correct #modloaded lines yet and I wanted to make sure you had everything you needed for them to work if you loaded it up in-game.

[Mekamancy-0.1a.zip](https://github.com/TheIllusiveC4/ConstructsArmory/files/2129662/Mekamancy-0.1a.zip)

Also, links to the Content Tweaker wiki:
https://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Tinkers_Construct/MaterialBuilder/
https://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Tinkers_Construct/TraitBuilder/

**Comment by TheIllusiveC4** [comment]
@Dragnier Thanks for that, it was very helpful for testing. Everything looks okay so far testing my integration implementation, now I just need to write up some docs so that people know how to use it.

**Comment by TheIllusiveC4** [comment]
The newest update has this integration, and the documentation is located [here](https://github.com/TheIllusiveC4/ConstructsArmory/wiki/ContentTweaker).
