### ISSUE TITLE
Suggestion: Adding custom armor

### ISSUE THREAD

**Issue by CobaltRealm** [TheIllusiveC4/ConstructsArmory#7]
I have an idea for the mod!

I've been playing with InfiniTic mod's functions and I've had an idea, the possibility to add your own armor, this could depend on the mod InfiniTic or could be added to the mod itself!

**Comment by CobaltRealm** [comment]
Here is a link to the wiki of the mod to see the format of the config file and how to use it:

https://github.com/LakMoore/InfiniTiC/wiki

**Comment by TheIllusiveC4** [comment]
Hey thanks for the suggestion. This is an interesting idea, but could get complicated with either path. It's a possibility though, so I'll keep this in mind. Since I would consider this a luxury feature, I probably won't get around to this until much later on.

**Comment by CobaltRealm** [comment]
Thanks! I think your mod has a lot of potential so keep going ;D

**Comment by TheIllusiveC4** [comment]
All things considered, I think this suggestion is probably best implemented on InfiniTiC's end since they already have such a system in place and I'd probably have to introduce a lot of redundancies to do this for my mod. If those developers need any help from me to do so, I'd be glad to assist.
