### ISSUE TITLE
Suggestion: Balance tweaks for early game

### ISSUE THREAD

**Issue by LordHellscream** [TheIllusiveC4/ConstructsArmory#70]
Suggestions: 
1. gives the "plate" part various degree of "overall small" bonus to armor rating, with zero bonus for cheap materials and proportionally more bonus based of relative strength of material being used (but bonus should be small overall), possible to balance the overall armor rating slightly to take into consideration of this bonus.

2. Allow armor to be repaired with material used for "plate" part in addition to "cores", so players can cheap it out like they could with tinker construct's tools by sacrificing some overall armor rating (15-20%) to allow repair with cheap materials. giving player more options early game.  

3. Base armor rating and durability for "cores" made of cheap material should be increased to something of leather level so they are not completely useless. but with some penalty. wood make you take more fire damage, burn longer. Stone make it take little more falling damage etc. (limit penalty only to cheap material though and balance that by raising their armor rating so they can semi useful early on).

**Comment by TheIllusiveC4** [comment]
I actually experimented with a version of 1 and 2 in pre-alpha. What I found was that the increased emphasis on armor rating by making two parts a contributing factor just made it even more likely that players would not branch out to a variety of materials and instead focus on armor rating alone.

As for 3, I'd rather not go this route as this penalty feature seems rather clunky in practice. How do you even draw the line between cheap materials and everything else? My preference is to simply make them have stronger traits if they're currently not viable early-game options.
