### ISSUE TITLE
Startup Crash with CraftTweaker and no ContentTweaker

### ISSUE THREAD

**Issue by dannydjdk** [TheIllusiveC4/ConstructsArmory#71]
#### Versions:
* Construct's Armory: 1.0.1
* Tinkers' Construct: 2.10.1.87
* Mantle: 1.3.2.24
* CraftTweaker: 4.1.9
* Forge: 14.23.4.2705

#### Observed Behavior:
Crash on startup when loaded with CraftTweaker and without ContentTweaker. The crash does not occur if CraftTweaker is removed or ContentTweaker is added.
 
#### Expected Behavior:
No crash. ContentTweaker code should not load if ContentTweaker is not included.

#### Steps to Reproduce:
1. Assemble pack with Construct's Armory and CraftTweaker (and dependencies) and no ContentTweaker.
2. Launch pack.

Crash Log: https://pastebin.com/JjF0tdd1

**Comment by TheIllusiveC4** [comment]
Ah, darn. I forgot to check for dependency crashes. Alright, I'm working on a fix right now.

**Comment by TheIllusiveC4** [comment]
Alright, new update should have this fixed. Sorry about that.
