### ISSUE TITLE
JEI Hiding Armor Forges Individually

### ISSUE THREAD

**Issue by Dragnier** [TheIllusiveC4/ConstructsArmory#72]
I am planning to only allow the iron based tool and armor forges in the pack I'm working on. I have modified the recipes so that is all you can make, but I like to hide the ones you can't to prevent confusion. With Tinkers, I can individually hide tool forges using the JEI menu to do so without all of them hiding. However, hiding any single armor forge from your mod hides them all.

In the JEI itemblacklist.cfg file:

tconstruct:toolforge:0:basemetals:zinc_block:0 <-- hides just this Zinc based tool forge (this is what using the hiding menu puts in the file for me when hiding Tinkers tool forges)

conarm:armorforge:0:basemetals:zinc_block:0  <-- doesn't hide anything (JEI puts conarm:armorforge only when hiding with the in-game menu)

**Comment by TheIllusiveC4** [comment]
Alright, just had to register the same table interpreter that Tinkers' uses for JEI for the Armor Forge. This will work as expected in the next update.
