### ISSUE TITLE
Wierd crash while loading

### ISSUE THREAD

**Issue by zzBuilderzz** [TheIllusiveC4/ConstructsArmory#73]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.0.1.1.jar
* Tinkers' Construct: 1.12.2-2.10.1.87.jar
* Mantle: 1.12-1.32.24.jar
* Forge: 14.23.3.2691

#### Steps to Reproduce:
1. download required mods above
2. put into mods folder
3. launch minecraft from launcher
...

Crash Log: https://pastebin.com/260T4tBr

**Comment by TheIllusiveC4** [comment]
Update to latest recommended Forge (14.23.4.2705)
