### ISSUE TITLE
Content Tweaker Integration Does Not Work

### ISSUE THREAD

**Issue by Dragnier** [TheIllusiveC4/ConstructsArmory#74]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory:  1.0.1.1
* Tinkers' Construct: 2.10.1.87
* Mantle: 1.3.2.24
* Forge: 14.23.4.2725

Reference #69 

#### Observed Behavior:
Content Tweaker integration does not work.

#### Expected Behavior:
Materials and Traits should register and appear in-game; both in the Tinkers/CA books and JEI.

#### Steps to Reproduce:
Here is another upload of my modpack with some altered scripts using your integration: 
[Mekamancy-0.1.1a.zip](https://github.com/TheIllusiveC4/ConstructsArmory/files/2143060/Mekamancy-0.1.1a.zip)

I've changed the AstralTinkerMats.zs and added AQArmorTrait.zs but nothing works. Even just trying to get the Materials to register without the traits errors. I will include a contenttweaker log below. I have even tried replacing the #loader contenttweaker with #loader conarm but that does even less...

You may really want to speak with the content tweaker author to get this working as it may take more than just copying the package and editing it.

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

[Content Tweaker Error Log](https://gist.github.com/Dragnier/076f384491b8c924ff9fe7d560f4e274)

**Comment by Dragnier** [comment]
Actually, I just found an error in my scripts that was causing this. I'm blind apparently... lol.

**Comment by TheIllusiveC4** [comment]
Just so you're fully aware, there are two errors. One is that you forgot to attach the method to the variable in AstralTinkerMats.zs down towards the bottom where `addTrimMaterials` is used. Second is that your armor trait in AQArmorTrait.zs uses the `onDamaged` function but forgets to return a suitable float value to represent the `newDamage` amount.

**Comment by Dragnier** [comment]
Yeah, I caught the first one and closed this as a result. Was just starting to work on the trait, so thanks catching that one; saved me a bit of time. Despite successfully making some mats and traits previously for Tinkers, I'm still rather new to Content Tweaker stuff.
