### ISSUE TITLE
Suggestion: Change parasitic to not cause the damage twitch effect

### ISSUE THREAD

**Issue by terrapin47** [TheIllusiveC4/ConstructsArmory#76]
Please see if you can change the damage taken from the parasitic ( necrotic bone ) modifier on armor to remove the damage twitch ( screen shake ) effect.  For an effect that will be constantly/intermittently ongoing until your armor is at full durability, it's very distracting and makes it hard to do other tasks.

Thanks.

**Comment by TheIllusiveC4** [comment]
I'll see what I can do, but I'm not sure I can without changing the behavior of the modifier entirely. I don't tell the parasitic modifier to damage you, I tell it to change your health directly, which still activates the effect. 

In addition, another thing to consider is that without the damage effect at all, players would not have any auditory indication that the modifier is stealing health. Players are accustomed to the fact that taking damage means that you get the twitching effect, so suddenly removing this may be counter-intuitive.

**Comment by kierajreed** [comment]
Maybe slow it down and increase something else?

**Comment by TheIllusiveC4** [comment]
I've tentatively decided on changing the behavior of the modifier to something like this: 

Parasitic will only activate when players are healed, rather than by stealing health. Parasitic will then heal the armor durability by absorbing a fraction of the healed amount for itself. The healed amount will be stronger than it is now to compensate for activating less often.

**Comment by terrapin47** [comment]
Sounds great 👍

**Comment by levilips123** [comment]
huh I like the idea . In fact I liked the old one too because it is basically a parasite . Using the host to keep itself alive by hurting it a little but not killing the host so that it can live longer
