### ISSUE TITLE
Crash when trying to use mod compiled from source

### ISSUE THREAD

**Issue by NamelessFTW** [TheIllusiveC4/ConstructsArmory#78]
Hey, I'm trying to build this mod from source but I keep crashing.
log file from .minecraft/logs/
[latest.log](https://github.com/TheIllusiveC4/ConstructsArmory/files/2149438/latest.log)
gist: https://gist.github.com/NamelessFTW/408900a209b39555c4680caf1a97407e

crash log file from .minecraft/crash-reports/
[crash-2018-06-29_13.42.33-client.txt](https://github.com/TheIllusiveC4/ConstructsArmory/files/2149435/crash-2018-06-29_13.42.33-client.txt)
gist: https://gist.github.com/NamelessFTW/04bd03d64fdd84010bd5612e9a09c727

Note, this does not happen if I use the runClient gradle task. I also realise that the log says that the file may have been tampered with since I am building it from source, but the code is unedited from the github sources.
Also, I'm a beginner to minecraft modding & gradle in general but am fairly experienced with Java, so I might be missing something really simple.
I am also using linux, in case that matters.

#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.0.1.1 from github (last commit is a5cae23)
* Tinkers' Construct: TConstruct-1.12.2-2.10.1.87
* Mantle: Mantle-1.12-1.3.2.24
* Forge: both 14.23.4.2725 (latest at time of writing) and 14.23.4.2725 (recommended at time of writing)

#### Observed Behavior:
Crashes with logs posted above

#### Expected Behavior:
No crash

#### Steps to Reproduce:
1. Download source code as ZIP file
2. Open in IntelliJ IDEA
3. Download ContentTweaker-1.12.2-4.6.0, CraftTweaker2-1.12-4.1.9, TinkerToolLeveling-1.12.2-1.0.5, ZenScript-4.1.8, base-1.12.2-3.9.0 into the ConstructsArmory-master/libs/ folder
4. In IDEA, run the build task in gradle
5. Copy the ConstructsArmory-master/build/libs/conarm-1.12.2-1.0.1.1.jar file into my mods folder
6. Run game outside of IDEA, with the mods in the versions section above
7. Game crashes during loading

Crash log posted at start of issue

Thanks

**Comment by TheIllusiveC4** [comment]
Since you stated that you are a beginner to Minecraft modding and I noticed you're missing a few key steps if your steps listed are accurate, did you first make sure that you set up a proper Forge modding environment? 

Here's a link to the documentation: [Forge - Getting Started](https://mcforge.readthedocs.io/en/latest/gettingstarted/)

**Comment by NamelessFTW** [comment]
OK got it working now but I'm not sure I've added the non-required mods (crafttweaker, tinker tool leveling, zenscript) properly, what is the proper way of doing this? I also can't find much documentation on how to add other mods to the dev environment so I can work on them as well, do you know of any resources I could use (or is it as simple as just adding them using the gradle menu and importing their gradle.build)?

Apart from that, feel free to close this issue.
Thanks.

**Comment by TheIllusiveC4** [comment]
That depends on what you intend to do with the optional mods. If you're just looking to run them together, you can just place it in the root /run folder and they'll be loaded. If you're looking to utilize them as a library, you can add them as a library to the root /libs folder (you might also need to add them to the project through the Project Structure menu). I'm not sure what you're asking for the second part, are you trying to edit the code of multiple mods in a single workspace? If so, I don't think that's possible.
