### ISSUE TITLE
Armors can not display normally when with mod TexFix.

### ISSUE THREAD

**Issue by xyy25** [TheIllusiveC4/ConstructsArmory#79]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.0.1.1
* Tinkers' Construct: 1.12.2-2.10.1.87
* Mantle: 1.12-1.3.2.24
* Forge: 14.23.4.2707

#### Observed Behavior: When TexFix exists, some dressed things (armors from vanilla and your or other mods, baubles included) can not display normally when one of the armor from your mod is dressed. The armor may be seen after I left and restart the game. But the newly made armors from the mod can still have the problem.

TexFix (CurseForge link: https://minecraft.curseforge.com/projects/texfix) is a mod that helps reduce memory used by delete useless textures. The version of this mod I use is V1.12-4.0.

#### Steps to Reproduce:
1.Initializing TexFix and the mods.
2.Enter the game and try to dress up different kinds of armors several times.
3.The armor dressed will display abnormally.
...

p.s: I'm not very good in English because I'm not from English-speaking countries. If you can't understand my expressions well, forgive me. And thank you for making this fantastic mod :).

**Comment by TehSeph** [comment]
Known bug. See #56. TexFix is also noted to have issues with Tinker's Construct without Construct's Armory.
