### ISSUE TITLE
Suggestion: Armor Modifiers for Bees Protection (Apiarist's Armor)

### ISSUE THREAD

**Issue by jorgemtz90** [TheIllusiveC4/ConstructsArmory#80]
Hello there! awesome work you did with this mod since long time paying modded Minecraft been waiting for an armor with tinker's style customization, now here's your mod, keep going the great work!.

I guess there's a lot of suggestions for different integrations for mods that people may be asking you and I don't really know if it is in the plans for the project you are developing to include this kind of interaction, but if this is going to be planed in the future I think it could be a great modifier part for the armor to include a protection to the bees from the forestry mod.

the way I was thinking was to use the same items that forestry use to create their armor and add a modifier to each part of the armor, it could be that once every part has this modifier the bees can no longer hurt you.

I hope if you are planning to make integrations with other mods this suggestion helps a bit for it

thanks for this awesome mod that I've been enjoyed since the release!

**Comment by TheIllusiveC4** [comment]
I'm not planning on adding modifiers for other mods, it would introduce too much bloat to the main mod. This would be more appropriate for an add-on.
