### ISSUE TITLE
Suggestion for Galacticraft & Addons

### ISSUE THREAD

**Issue by Preminenc3** [TheIllusiveC4/ConstructsArmory#81]
It would be really cool if you could make some sort of modifier to add to armor that will stop pressure dmg and slow radiation gain like the Galacticraft space suits so you don't have to change back and forth when traveling to planets.

**Comment by TheIllusiveC4** [comment]
Unfortunately, I won't be adding any modifiers or materials for other mods.

**Comment by kierajreed** [comment]
Fortunately, you can make an add-on to do just that, or ask someone else to do it for you!
