### ISSUE TITLE
[1.12.2-1.0.1.1] When using boots with High Stride, sneak no longer prevents falls

### ISSUE THREAD

**Issue by JaSpr** [TheIllusiveC4/ConstructsArmory#82]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.0.1.1
* Tinkers' Construct: 1.12.2-2.10.187
* Mantle: 1.3.2.24
* Forge: 14.23.4.2708

#### Observed Behavior:
When using boots with High Stride, users cannot use sneak to stay on a block

#### Expected Behavior:
When sneaking to the edge of a block (like over lava), the user should not be able to fall off.  

#### Steps to Reproduce:
1. Equip boots with high stride.
2. Sneak to a ledge to try to extend out past the ledge.
3. Fall to your doom.

**Comment by TheIllusiveC4** [comment]
Alright, this was just a result of me not knowing that the ability to sneak to prevent falling off a block is based off of the step height. This will be fixed in the next update.
