### ISSUE TITLE
Traveller's Belt as seperate mod

### ISSUE THREAD

**Issue by UnPure** [TheIllusiveC4/ConstructsArmory#83]
I know github is usually not the right place for this question/request but i couldnt find a different way to get in contact (Discord/IRC).
Back when it was part of the main TConstruct mod, i loved the Traveller's Belt and missed it a lot on later MC versions. Sadly i dont really have a use for the full Construct's Armory mod but still would love to have a way to use the Traveller's Belt. Is there any chance to see the belt as a seperate mod as a Baubles accessoire?
I know that the belt currently isnt a Baubles accessoire so i dont know how much work it would be to change the belt from a modifier to a Baubles accessoire.

**Comment by TheIllusiveC4** [comment]
Check out [FannyPack](https://minecraft.curseforge.com/projects/fannypack)
