### ISSUE TITLE
Minecraft Crashes on Phase #2

### ISSUE THREAD

**Issue by PulseBeat02** [TheIllusiveC4/ConstructsArmory#84]
Hi, I was talking to the Crafttweaker mod creator, and he said that the problem is related to your mod. Here is the source: **https://github.com/CraftTweaker/CraftTweaker/issues/579** 
Be sure to check the website to find more information about this problem

Versions:
*** Construct's Armory: 1.0.1.2 
* Tinkers' Construct: 2.10.1.87
* Mantle: 1.3.2.24
* Forge: 14.23.4.2726**

I am using Minecraft 1.12.2

Observed Behavior:

The modpack I created crashes on phase two while loading all of the mods. 

Expected Behavior:

I expected the modpack to load properly and not crash Minecraft.

Crash Log: **https://pastebin.com/VeGD8g2j**

**Comment by TheIllusiveC4** [comment]
This is not an issue with Construct's Armory, you're simply using an outdated version of ContentTweaker. You're using 4.5.0, the latest version is 4.6.0. In the future, make sure to update all related mods to the latest version before submitting issues to rule out problems such as this.

However, I will update the dependency information on Construct's Armory side to make this clearer to users which version of ContentTweaker is required.

**Comment by PulseBeat02** [comment]
@TheIllusiveC4 I'm sorry for posting this issue without updating my mods. Next time, I promise I will try to rule out problems like this.
