### ISSUE TITLE
Issue: Wrong cloak description

### ISSUE THREAD

**Issue by YueLengM** [TheIllusiveC4/ConstructsArmory#85]
When i was translating this mod, I found a wrong cloak description.
![snipaste_180705_230501](https://user-images.githubusercontent.com/11801894/42331326-bec6393e-80a7-11e8-8ce5-ee593b56d6ee.png)

**Comment by TheIllusiveC4** [comment]
Good catch. The correct description should be: "For explorers who want to sneak around, this cloak will grant them the ability to disappear from plain sight."
