### ISSUE TITLE
Mod crashes Minecraft with Crafttweaker installed.

### ISSUE THREAD

**Issue by OneTwoMint** [TheIllusiveC4/ConstructsArmory#87]
#### Versions:
* Construct's Armory: conarm-1.12.2-1.0.1.2
* Tinkers' Construct: TConstruct-1.12.2-2.10.1.87
* Mantle: Mantle-1.12-1.3.2.24
* Forge: 14.23.4.2708 
* CraftTweaker: CraftTweaker2-1.12-4.1.5

#### Observed Behavior:
I launch Minecraft. It begins loading mods, as indicated by the appropriate loading screen from Forge. The window closes and I am sent to the launcher.
#### Expected Behavior:
I launch Minecraft. The mods are loaded, and the game begins.
#### Steps to Reproduce:
1. Have necessary mods for Construct's Armory installed.
2. Have Crafttweaker installed.
3. Attempt to run Minecraft.

Crash Log: https://gist.github.com/Milomus2/1e20c675a73f0e5277c9876b52ce4ecb

**Comment by TheIllusiveC4** [comment]
You're using an outdated version of CraftTweaker. Your version is 4.1.5, the latest version is 4.1.9. Please update and try loading again. In the future, please make sure that all mods are updated to the latest version before submitting issues.
