### ISSUE TITLE
Necrotic Modifier replaced

### ISSUE THREAD

**Issue by Soldra** [TheIllusiveC4/ConstructsArmory#9]
Currently the mod replaces the Necrotic modifier from the necrotic bone with the parasitic modifier, which doesn't work on tools.
Please try to work this out, since it makes my weapons less useful

**Comment by TheIllusiveC4** [comment]
Huh, weird. I don't know why this would affect only this modifier and not the other ones. Anyway, I'll get this fixed.

**Comment by TheIllusiveC4** [comment]
After working through this for a while, I've realized that the Tinkers system wasn't really built to accommodate multiple modifiers attached to a single item. I'm trying to figure out a workaround, but worst case scenario is that I'll have to make brand new items to house all of the armor modifiers.
