### ISSUE TITLE
[Request] Horse Armor / Saddles

### ISSUE THREAD

**Issue by Pabilo8** [TheIllusiveC4/ConstructsArmory#93]
Just as the title says, it would protect the horse and give it special abilities, like higher speed, jump, protection or maybe even elytra-like gliding ability or ability to bounce like slime boots.
There are many posibilites, like additional chests-sacks on the sides of the horse, or maybe even ender chests?
While armor would give buffs to the horse, a saddle could effect the rider, maybe giving them regeneration, resistance or night vision. 
Also low-level saddles (made of wood or stone) could effectively encourage the player to ride a horse in he early game.

**Comment by TheIllusiveC4** [comment]
This is a suggestion that I've been told before and I think it has potential. But I'm not looking to add something like this at this time. I'll give it a shot after I've mostly finished updating the player armor content, whenever that is.
