### ISSUE TITLE
Suggesion: For the Soul Sight, maybe it should use the Glowing effect instead of a new particle?

### ISSUE THREAD

**Issue by aaronhowser1** [TheIllusiveC4/ConstructsArmory#94]
It would be easier to see mobs like that, and it would use more vanilla mechanics instead of having to make a new one

**Comment by TheIllusiveC4** [comment]
I toyed with a version like that early in the development of the Soul Sight. 

Personally, my main issue is that the Glowing effect is universal, which means everyone can see them. Of course I could try to replicate this effect for the wearer only, but having two identical effects that operate differently isn't great for intuitiveness.

I don't really feel that strongly about this though, so I'm quite willing to reconsider if the arguments are strong enough or the overall consensus is in favor of it.

**Comment by aaronhowser1** [comment]
Botania's Third Eye does this, though I'm not sure if the effect is visible to players that don't have it and I don't have anyone to test it with.

**Comment by TheIllusiveC4** [comment]
Botania's Third Eye simply applies the Glowing potion effect, so it is indeed visible to players that don't have it. In addition, this also does not address my concern about having two identical effects with different behavior.

**Comment by kierajreed** [comment]
Maybe special particles? Or a HUD overlay?

**Comment by aaronhowser1** [comment]
@SkyHawkB That's how it works right now, you hit a button and a special particle that you can see through blocks shows up wherever a mob is.
