### ISSUE TITLE
Travellers Cloak (invisibility) don't work on Armor

### ISSUE THREAD

**Issue by Dalari88** [TheIllusiveC4/ConstructsArmory#97]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.0.1.2
* Tinkers' Construct: 2.10.1.87
* Mantle: 1.3.2.24
* Forge: 2.4.2.60-Universal

#### Observed Behavior:
Traveller's Cloak (invisibility) don't work correct. Charakter become invisible but the full Armor is visible after all so that the invisibly haven't any effect on mobs or other players

#### Expected Behavior:
The Armor should become invisible like the charakter as well. Otherwise there is no point in this modification.

#### Steps to Reproduce:
1. Get a Armor with Traveller's Cloak (invisibility)
2. Try to activate the Cloak

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
The Invisiblity Cloak works correctly, as it simply adds the Invisibility potion effect to players. The only issue is the presence of armor weakens the invisibility effect, but the fact that it's invisible or not does not have any effect on mob detection. The simple act of wearing the armor is what weakens the invisibility effect, but there's a small sneaking buff to the cloak to offset this.

As for player detection, I think I was supposed to make the chestpiece invisible but forgot to do so during the last update.

**Comment by Dalari88** [comment]
My Point is the effect don't work on mobs. I just testet it again. I'm invisible and the mob look direktly on me and attacks me.

**Comment by TheIllusiveC4** [comment]
What are you wearing when that happens? The more armor you wear, the more easily mobs can detect you. This is simply vanilla behavior.

I just tested this myself and with only one piece of armor, the Invisibility Cloak itself, I can move around mobs just fine without being detected.

**Comment by Dalari88** [comment]
Ok, my bad. i have tested it full armored. With only the Chestplate it works fine only the chestplate is visible after all so against players it have no effect. Would love to see the chestplate, maybe the full armor disappear if the cloak is activ.

**Comment by TheIllusiveC4** [comment]
The next update will have the chestplate disappear as well, so at least it will be more effective against player detection. I do plan to make the full armor disappear eventually as well, but I'll need to submit a PR to Forge first in order to get the functionality that I want.
